/**
 * Canonical inventory of features built into O.C.R.P.
 * Used by the in-app Feature Checklist page and PDF export.
 */

export type FeatureCategory = {
  id: string;
  title: string;
  description: string;
  features: string[];
};

export const FEATURE_CHECKLIST: FeatureCategory[] = [
  {
    id: 'character',
    title: 'Character System',
    description: 'Creating, importing, and evolving original characters.',
    features: [
      'Guided 6-step character creation wizard (Identity, Origin, Power, Personality, Backstory, Review)',
      'Legacy full-form character editor available via ?advanced=1',
      'AI-powered character notes parser (paste raw notes → structured stats)',
      'Character notes & memory refinement (Move Clarification, Personality, Tactics)',
      '8-stat system (0–100) plus separate Battle IQ',
      'Automated stat scaling driven by the engine',
      'Sex & gender-aware pronoun and narration logic',
      'Character alignment system (hidden archetype tags)',
      'Character timeline & appearance system',
      'Identity Discovery Engine + Character Psychology Engine',
      'Personal Trigger System (environmental cues tied to backstory)',
      'Personal book / character sheet PDF download',
      '3D character generation pipeline',
      'AI character background generation',
      'Character directory and personal character list',
      'Character image uploads and gallery',
      'Character constructs (persistent objects, barriers, summons)',
      'Character groups for organizing your roster',
    ],
  },
  {
    id: 'battle',
    title: 'Battle System (R.O.K. Engine)',
    description: 'Tactical, narrative-driven combat across multiple modes.',
    features: [
      'Comprehensive Battle Brain with PvP, PvPvP, PvE, EvE, and Campaign Exploration modes',
      'Tactical Battle Map: dual-mode 2D SVG and 3D Mythic Symbolic procedural rendering',
      'Zone-based battlefield model with named logical spaces',
      'Combat Layer System for spatial resolution',
      'Distance & positioning system (melee 0–2m through extreme 50–200m)',
      'Battle tier system v3 (1–7 scaling, Tier 4+ requires intrinsic powers)',
      'Dice system, hit detection, charge attacks, environment interactions',
      'Momentum and Psychological Warfare subsystems',
      'Overcharge mechanic (⚡ toggle, 1.5–2x potency, higher risk)',
      'Concentration mechanic (limited resource to influence rolls)',
      'Status effects with visual blocks (Airborne, etc.)',
      'Defense Validation and Hard Clamp move validation',
      'NPC opponent AI brain (dodge, hide, strike, feint)',
      'Group PvP / 3-player battles with deterministic 1-2-3 turn cycle',
      'EvE simulation, Mock battles, Group battle creation',
      'Procedural ambient sound engine (Web Audio API)',
      'Real-time battle challenge notifications',
      'Battle SFX system',
    ],
  },
  {
    id: 'campaign',
    title: 'Campaign Mode',
    description: 'Long-form narrative play with a single Narrator intelligence.',
    features: [
      'Single Narrator Intelligence delivering structured scene beats',
      'Persistent Campaign HUD (story arc, time/day, status)',
      'Scene Recap card on session entry/re-entry',
      'AI-driven campaign creation and seeding from a user description',
      '100-NPC pool generated per campaign',
      'Smart NPC dialogue system (context-aware conversations)',
      'Unified Action Roll System and Outcome Bands',
      'Context-aware intent detection (prevents keyword false-positives)',
      'Campaign response suggestions (collapsible AI suggestions above input)',
      'Campaign concentration mechanic',
      'Gated Opportunities + Story Hooks lifecycle',
      'Temporal logic (0–3 action-based time blocks)',
      'Discovery system for traits, lore, and abilities',
      'Regional Social Heat and emotional layers',
      'Location Identity System (Terrain, Tone, Control)',
      'Narrative Pressure Engine (5 tension levels)',
      'Narrative Thread Engine (mystery/threat/character/moral/world)',
      'Lore Consistency Engine',
      'XP and immediate leveling system',
      'Campaign visibility tiers (Public / Friends-Only / Private)',
      'Join Request system (Pending / Accepted / Declined)',
      'Multiplayer item trading (Offer & Accept, zone-restricted)',
      'Campaign inventory and item discovery',
      'Real-time campaign messaging with optimistic UI',
    ],
  },
  {
    id: 'world',
    title: 'World & Map Systems',
    description: 'Procedural environments and terrain that evolves with the story.',
    features: [
      'Mythic Symbolic 3D world map (Google-Maps style zoom)',
      'Normalized 3-layer map architecture',
      'BiomeComposer + UrbanStructureComposer for procedural arenas',
      'Visual Identity System (material and lighting consistency)',
      'Narrator-Aware Terrain Mutation Engine (real-time battlefield changes)',
      'Scene location tracking (chat background syncs to narrative)',
      'Random location generator + emergency location generator',
      'Planet generator, terrain, and physics',
      'Solar system visualization',
      'Architecture Families and Material Palettes for urban areas',
    ],
  },
  {
    id: 'narration',
    title: 'Chat, Narration & Voice',
    description: 'Immersive in-character communication and audio.',
    features: [
      'Advanced Chat Expression System (data-driven visual packets)',
      'Speaker Presentation Profile runtime authority',
      'Narrator voice (text-to-speech) via ElevenLabs',
      'Procedural ambient SFX based on narrative context',
      'Voice input on chat and character creation fields',
      'Real-time messaging with optimistic UI and reconciliation',
      'Real-time typing/feedback indicators',
      'NPC dialogue parser',
      'Narrator markers and voice scripts',
      'Message normalization pipeline (separates narrator vs NPC)',
      'NPC name discovery resolution at render-time',
    ],
  },
  {
    id: 'lore',
    title: 'Lore & Worldbuilding',
    description: 'Tools for building and consuming the universe.',
    features: [
      'Lore document upload with AI parsing',
      'Species/race system with hierarchical sub-races',
      'Species discovery and linking',
      'Interactive 3D Living Rulebook (animated page-flip)',
      'Living Rulebook Registry',
    ],
  },
  {
    id: 'social',
    title: 'Social & Community',
    description: 'Connecting players and gathering ideas.',
    features: [
      'Friends system with Friends panel',
      'Teams, Stories, and Throne Room pages',
      'User profiles + public username profile pages',
      'Global Community Suggestions (header "Ideas" button, upvote system, one-vote enforcement)',
      'Creator welcome banner',
      'Real-time friend and challenge notifications',
    ],
  },
  {
    id: 'auth',
    title: 'Auth & Onboarding',
    description: 'How users get into the app.',
    features: [
      'Standard email/password auth with password reset flow',
      '5-step guest onboarding flow for logged-out visitors (sessionStorage drafts)',
      'Activity tracker (powers Founder Pass eligibility)',
      'Tester mode with slash commands and abandonment detection',
      'Role-based access: admin, moderator, user (separate user_roles table)',
    ],
  },
  {
    id: 'monetization',
    title: 'Monetization',
    description: 'Subscriptions, donations, and founder rewards.',
    features: [
      'Stripe AI-access subscriptions (multiple tiers)',
      'Custom-amount donations via Stripe Checkout',
      'Membership management page + customer portal',
      'Founder Legacy Status badges for early users',
      '25-spot Founder Pass with 5-day activity confirmation',
    ],
  },
  {
    id: 'admin',
    title: 'Admin & Diagnostics',
    description: 'Internal tools for managing the app.',
    features: [
      'Admin panel with user/role management and battle moderation',
      'Secure admin_set_user_role RPC (server-side authorization)',
      'System Architecture page (interactive diagram, user flows, table inventory)',
      'Feature Checklist page with PDF export',
      'Intent Debug + Action Resolution Debug UIs',
      'Settings page with user preferences',
      'Password gate protecting admin and internal pages',
    ],
  },
  {
    id: 'security',
    title: 'Security & Infrastructure',
    description: 'Foundations that keep the app safe and reliable.',
    features: [
      'AES-256 server-side encryption (pgcrypto) for user-created content',
      'Row-Level Security policies on every table',
      'AI Gateway with multi-model fallback for resilience and cost optimization',
      'Lovable Cloud backend (database, auth, edge functions, storage)',
      'Real-time subscriptions for notifications and messages',
      'Edge function suite: story-orchestrator, battle-narrator, parse-character-notes, narrator-tts, ambient-sfx, stripe checkout/portal/donation, 3D generation',
    ],
  },
  {
    id: 'design',
    title: 'Design System',
    description: 'Visual identity and component library.',
    features: [
      'Dark cosmic aesthetic (nebula gradients, cosmic-gold accents)',
      'HSL semantic tokens in index.css and tailwind.config.ts',
      'Glass-morphism UI for campaign mode',
      'Page transitions and breadcrumb navigation',
      'Mobile-first responsive battle interface',
      'Custom shadcn component variants',
    ],
  },
];

export function getTotalFeatureCount(): number {
  return FEATURE_CHECKLIST.reduce((sum, c) => sum + c.features.length, 0);
}
