/**
 * Extended Emergency Blueprints — Human-Caused & Grounded Catalog
 *
 * Fills the gaps in the original `emergencyBlueprints.ts` catalog, which
 * skewed heavily toward physical / natural / industrial disasters. These
 * 80+ entries cover the *human* danger families the original catalog was
 * missing: criminal incidents, terrorist sabotage, political/civil unrest,
 * transportation crises (granular), public-systems failures, mass panic,
 * survival breakdown, biological hazards, technological malfunction.
 *
 * Each entry authors the new taxonomy fields directly (family,
 * groundedness, objectives, escalationPath, combatFrame, enemyPressure,
 * dominantImagery) so the selector doesn't have to infer them.
 *
 * Pure data — Deno + browser compatible.
 */

import type { EmergencyBlueprint } from './emergencyBlueprints.ts';
import type { DangerTaxonomyFields } from './dangerTaxonomy.ts';

export type ExtendedBlueprint = EmergencyBlueprint & DangerTaxonomyFields;

export const EXTENDED_EMERGENCY_BLUEPRINTS: ExtendedBlueprint[] = [
  // ── CRIMINAL INCIDENT ────────────────────────────────────────────────────
  {
    id: 'crim-bank-hostage-siege',
    title: 'Downtown Bank Hostage Siege',
    concept: 'Armed robbers barricade thirty hostages inside a glass-walled bank as police perimeter tightens.',
    category: 'crowd-panic', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['urban','glass','hostage','gunfire','crowd'],
    timePressure: ['executions threatened every five minutes','SWAT entry window closing'],
    movementConstraints: ['hostage human shields','sniper sightlines through plate glass','pressure-plate alarms'],
    collateral: ['cashiers facedown on marble','child clutching mother in lobby','wounded guard bleeding out'],
    dynamicFactors: ['accomplice in getaway van outside','silent alarm triggering reinforcements'],
    family: 'criminal-incident', groundedness: 'grounded',
    objectives: ['rescue','neutralization','civilian-protection'],
    escalationPath: ['enemy-reinforcement','panic-crush','public-order-collapse'],
    combatFrame: ['civilian-presence-constraint','sightline-occlusion','cover-degradation'],
    enemyPressure: ['armed-criminals'],
    dominantImagery: ['glass','blood','urban','gunfire'],
  },
  {
    id: 'crim-cartel-warehouse-raid',
    title: 'Cartel Warehouse Raid Gone Wrong',
    concept: 'A drug-lab raid turns into a chemical inferno when defenders ignite their own product to cover escape.',
    category: 'crowd-panic', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 2, maxTier: 4,
    tags: ['industrial','fire','chemical','gunfire','smoke'],
    timePressure: ['accelerant tanks rupturing','cartel reinforcements ten minutes out'],
    movementConstraints: ['stacked pallets blocking sightlines','toxic vapor pooling in low corners','wet concrete underfoot'],
    collateral: ['undercover officer wounded','migrant lab workers locked in back room'],
    dynamicFactors: ['secondary precursor explosion','rooftop sniper repositioning'],
    family: 'criminal-incident', groundedness: 'grounded',
    objectives: ['neutralization','rescue','containment'],
    escalationPath: ['spreading-fire','toxic-spread','enemy-reinforcement'],
    combatFrame: ['environmental-weaponization','sightline-occlusion','cover-degradation'],
    enemyPressure: ['armed-criminals'],
    dominantImagery: ['fire','smoke','chemical','gunfire'],
  },
  {
    id: 'crim-prison-riot-blackout',
    title: 'Prison Riot During Coordinated Blackout',
    concept: 'Cellblocks open simultaneously when a synchronised power cut kills the lock grid.',
    category: 'crowd-panic', scope: 'district', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 4,
    tags: ['urban','crowd','blood','metal','rubble'],
    timePressure: ['guards being overrun cell by cell','medical wing siege in seven minutes'],
    movementConstraints: ['shiv-wielding mobs in narrow tiers','barricaded stairwells','laundry-cart obstacles'],
    collateral: ['hostage guards bound on B-block','infirmary patients trapped'],
    dynamicFactors: ['fire set in commissary','warden taken hostage by faction leader'],
    family: 'criminal-incident', groundedness: 'grounded',
    objectives: ['rescue','neutralization','containment','recon-in-chaos'],
    escalationPath: ['enemy-reinforcement','spreading-fire','public-order-collapse'],
    combatFrame: ['cover-degradation','sightline-occlusion','mobility-restriction','civilian-presence-constraint'],
    enemyPressure: ['panicked-mob','armed-criminals'],
    dominantImagery: ['blood','metal','crowd'],
  },
  {
    id: 'crim-armored-car-ambush',
    title: 'Armored Car Ambush at Freeway Off-Ramp',
    concept: 'A coordinated ramming and shotgun ambush pins an armored transport on a busy off-ramp at rush hour.',
    category: 'transport-crisis', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['urban','vehicle','gunfire','metal','glass'],
    timePressure: ['gas leak from tipped sedan','crew bleeding inside cabin'],
    movementConstraints: ['stalled rush-hour traffic','overturned vehicles as cover','crossfire lanes'],
    collateral: ['commuters trapped in cars','baby seat in nearby SUV'],
    dynamicFactors: ['second crew arriving on motorcycles','helicopter overhead'],
    family: 'criminal-incident', groundedness: 'grounded',
    objectives: ['neutralization','rescue','civilian-protection'],
    escalationPath: ['enemy-reinforcement','spreading-fire','panic-crush'],
    combatFrame: ['cover-degradation','civilian-presence-constraint','sightline-occlusion'],
    enemyPressure: ['armed-criminals'],
    dominantImagery: ['vehicle','glass','urban','gunfire'],
  },
  {
    id: 'crim-kidnap-warehouse',
    title: 'Kidnap Compound Hidden in Industrial Park',
    concept: 'A children\'s ransom holding-cell discovered behind sheet-metal walls of a working machine shop.',
    category: 'crowd-panic', scope: 'local', intensity: 'rising', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['industrial','metal','dust','blood','urban'],
    timePressure: ['captors moving children to a van','operator at the workshop a paid lookout'],
    movementConstraints: ['sheet-metal partitions','grease-slick floor','overhead crane gantries'],
    collateral: ['eleven children in single locked room','female translator gagged on cot'],
    dynamicFactors: ['second cell phoning escalation','fire set in tool crib to destroy evidence'],
    family: 'criminal-incident', groundedness: 'grounded',
    objectives: ['rescue','neutralization','recon-in-chaos'],
    escalationPath: ['enemy-reinforcement','spreading-fire'],
    combatFrame: ['sightline-occlusion','civilian-presence-constraint','cover-degradation'],
    enemyPressure: ['armed-criminals'],
    dominantImagery: ['metal','urban','blood'],
  },
  {
    id: 'crim-arson-row-housing',
    title: 'Arson Spree Through Row Housing',
    concept: 'A serial arsonist torches a strip of attached houses in sequence, fire jumping party walls.',
    category: 'fire-conflagration', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['fire','smoke','urban','wood','rubble'],
    timePressure: ['fire reaching gas meters','arsonist still on the block'],
    movementConstraints: ['shared attics carrying fire','narrow alleys clogged with bins','collapsing porches'],
    collateral: ['elderly resident in third house','dog barking from fourth'],
    dynamicFactors: ['accelerant cans planted ahead','copycat lighting opposite row'],
    family: 'criminal-incident', groundedness: 'grounded',
    objectives: ['rescue','neutralization','civilian-protection'],
    escalationPath: ['spreading-fire','structural-cascade','enemy-reinforcement'],
    combatFrame: ['shifting-hazard-zones','sightline-occlusion','timed-pressure'],
    enemyPressure: ['armed-criminals'],
    dominantImagery: ['fire','smoke','urban'],
  },
  {
    id: 'crim-courthouse-shootout',
    title: 'Courthouse Shootout Mid-Trial',
    concept: 'A defendant\'s crew storms an active courtroom to free him, jury and judge pinned in chambers.',
    category: 'crowd-panic', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['urban','glass','gunfire','blood','crowd'],
    timePressure: ['marshals running out of ammunition','bailiff bleeding behind bench'],
    movementConstraints: ['fixed pews as cover','marble corridors echoing fire','elevator lockdown'],
    collateral: ['jurors barricaded in deliberation room','court reporter wounded'],
    dynamicFactors: ['secondary breach at judge\'s parking entrance','gas grenade thrown into hallway'],
    family: 'criminal-incident', groundedness: 'grounded',
    objectives: ['neutralization','rescue','civilian-protection','defensive-hold'],
    escalationPath: ['enemy-reinforcement','panic-crush','communication-blackout'],
    combatFrame: ['cover-degradation','civilian-presence-constraint','sightline-occlusion'],
    enemyPressure: ['armed-criminals'],
    dominantImagery: ['urban','blood','gunfire','glass'],
  },
  {
    id: 'crim-mall-active-shooter',
    title: 'Active Shooter in Three-Level Shopping Mall',
    concept: 'Two shooters move opposite directions through a packed mall during weekend foot traffic.',
    category: 'crowd-panic', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['urban','glass','crowd','blood','gunfire'],
    timePressure: ['casualty count climbing every minute','escalator pile-up at exit'],
    movementConstraints: ['fleeing crowds blocking corridors','shattered storefronts','jammed stairwells'],
    collateral: ['food-court diners under tables','infants in stroller convoy'],
    dynamicFactors: ['third shooter possible','fire alarm masking gunfire location'],
    family: 'mass-panic-event', groundedness: 'grounded',
    objectives: ['neutralization','civilian-protection','rescue'],
    escalationPath: ['panic-crush','public-order-collapse','enemy-reinforcement'],
    combatFrame: ['civilian-presence-constraint','sightline-occlusion','rescue-priorities'],
    enemyPressure: ['armed-criminals','panicked-mob'],
    dominantImagery: ['urban','glass','crowd','blood'],
  },
  {
    id: 'crim-night-club-ambush',
    title: 'Nightclub Mass Casualty Ambush',
    concept: 'Multiple attackers open fire at a packed nightclub then barricade exits.',
    category: 'crowd-panic', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['urban','neon','blood','crowd','smoke'],
    timePressure: ['exits being chained shut','wounded bleeding on dance floor'],
    movementConstraints: ['strobe-lit darkness','pile of bodies near main door','spilled drinks underfoot'],
    collateral: ['hundreds of patrons','staff trapped behind bar'],
    dynamicFactors: ['fire set near DJ booth','suicide vest threat from second attacker'],
    family: 'terrorist-sabotage', groundedness: 'grounded',
    objectives: ['neutralization','rescue','civilian-protection'],
    escalationPath: ['spreading-fire','panic-crush','enemy-reinforcement'],
    combatFrame: ['sightline-occlusion','civilian-presence-constraint','cover-degradation'],
    enemyPressure: ['organized-militants','armed-criminals'],
    dominantImagery: ['neon','blood','crowd','smoke'],
  },
  {
    id: 'crim-gang-territory-firefight',
    title: 'Gang Territory Firefight Spilling Through Apartments',
    concept: 'Two gangs trade fire across a low-rise block, rounds tearing through paper-thin apartment walls.',
    category: 'crowd-panic', scope: 'district', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['urban','blood','gunfire','rubble','crowd'],
    timePressure: ['ricochet casualties mounting in stairwells','reinforcements rolling in'],
    movementConstraints: ['narrow corridors','laundry lines and parked cars as cover','elevators shut down'],
    collateral: ['families hiding in bathtubs','children in school bus stuck on the corner'],
    dynamicFactors: ['third faction joining','gas leak from punctured stove'],
    family: 'criminal-incident', groundedness: 'grounded',
    objectives: ['neutralization','civilian-protection','rescue'],
    escalationPath: ['enemy-reinforcement','spreading-fire','public-order-collapse'],
    combatFrame: ['cover-degradation','civilian-presence-constraint','sightline-occlusion'],
    enemyPressure: ['armed-criminals'],
    dominantImagery: ['urban','blood','gunfire'],
  },

  // ── TERRORIST SABOTAGE ───────────────────────────────────────────────────
  {
    id: 'terror-subway-vest-attack',
    title: 'Suicide Vest in Underground Metro Train',
    concept: 'A militant boards a packed metro car at peak hour with a wired vest and dead-man switch.',
    category: 'transport-crisis', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['tunnel','crowd','urban','metal','smoke'],
    timePressure: ['dead-man switch held under thumb','train accelerating into tunnel'],
    movementConstraints: ['standing-room-only crowd','locked car doors','single sightline to attacker'],
    collateral: ['hundreds of commuters','child near attacker'],
    dynamicFactors: ['accomplice on next platform','tunnel ventilation failure post-blast'],
    family: 'terrorist-sabotage', groundedness: 'grounded',
    objectives: ['neutralization','civilian-protection','rescue'],
    escalationPath: ['structural-cascade','panic-crush','spreading-fire'],
    combatFrame: ['civilian-presence-constraint','timed-pressure','sightline-occlusion'],
    enemyPressure: ['organized-militants'],
    dominantImagery: ['tunnel','crowd','urban','metal'],
  },
  {
    id: 'terror-bomb-train-station',
    title: 'Multiple Pressure-Cooker Devices in Central Station',
    concept: 'Synchronised IEDs hidden in luggage at a major train terminal, two already detonated.',
    category: 'urban-collapse', scope: 'district', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['urban','rubble','smoke','blood','metal','glass'],
    timePressure: ['third device timer visible','hundreds wounded in concourse'],
    movementConstraints: ['glass shrapnel field','collapsed concourse mezzanine','fleeing crowd'],
    collateral: ['mass casualties on platforms','rescue teams under fire from sniper'],
    dynamicFactors: ['secondary device targeting first responders','sniper covering exits'],
    family: 'terrorist-sabotage', groundedness: 'grounded',
    objectives: ['neutralization','rescue','cascade-interruption','civilian-protection'],
    escalationPath: ['structural-cascade','panic-crush','enemy-reinforcement'],
    combatFrame: ['timed-pressure','civilian-presence-constraint','sightline-occlusion','rescue-priorities'],
    enemyPressure: ['organized-militants'],
    dominantImagery: ['urban','rubble','smoke','blood'],
  },
  {
    id: 'terror-water-supply-poisoning',
    title: 'Reservoir Sabotage at City Water Supply',
    concept: 'Saboteurs release a contaminant into a city reservoir hours before morning consumption.',
    category: 'chemical-radiological', scope: 'city', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 4,
    tags: ['water','chemical','toxin','urban','wilderness'],
    timePressure: ['valves opening to distribution at dawn','contaminant dispersing through depth'],
    movementConstraints: ['floating walkways','treatment-plant pipework','barbed perimeter'],
    collateral: ['a million downstream consumers','hospital dialysis patients on supply'],
    dynamicFactors: ['armed sentries on shore','remote detonator on intake gates'],
    family: 'terrorist-sabotage', groundedness: 'grounded',
    objectives: ['cascade-interruption','neutralization','containment','civilian-protection'],
    escalationPath: ['toxic-spread','enemy-reinforcement','public-order-collapse'],
    combatFrame: ['timed-pressure','environmental-weaponization','sightline-occlusion'],
    enemyPressure: ['organized-militants'],
    dominantImagery: ['water','chemical','toxin'],
  },
  {
    id: 'terror-power-grid-substation',
    title: 'Coordinated Substation Sabotage Across the Grid',
    concept: 'Three substations hit within minutes — transformers shot through, threatening week-long outages.',
    category: 'energy-overload', scope: 'regional', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 4,
    tags: ['electric','industrial','wilderness','metal','smoke'],
    timePressure: ['cascade tripping more substations','militants moving to fourth target'],
    movementConstraints: ['live downed lines','arc-flash hazard zones','remote rural access roads'],
    collateral: ['hospitals on backup','traffic chaos in city','vulnerable populations on medical equipment'],
    dynamicFactors: ['booby-trapped fence','drone surveillance overhead'],
    family: 'terrorist-sabotage', groundedness: 'grounded',
    objectives: ['cascade-interruption','neutralization','infrastructure-preservation'],
    escalationPath: ['communication-blackout','public-order-collapse','enemy-reinforcement'],
    combatFrame: ['environmental-weaponization','timed-pressure','sightline-occlusion'],
    enemyPressure: ['organized-militants'],
    dominantImagery: ['electric','industrial','smoke','metal'],
  },
  {
    id: 'terror-stadium-attack',
    title: 'Coordinated Attack on Sold-Out Stadium',
    concept: 'Gunmen at multiple entrances open fire as a championship match concludes.',
    category: 'crowd-panic', scope: 'district', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['urban','crowd','blood','smoke','rubble'],
    timePressure: ['crowd surge toward bottlenecks','possible secondary device in concourse'],
    movementConstraints: ['concrete switchback ramps','tightly-packed crowd','locked emergency gates'],
    collateral: ['eighty thousand spectators','medical wing overrun'],
    dynamicFactors: ['hostage-taking on field','VIP box targeted'],
    family: 'terrorist-sabotage', groundedness: 'grounded',
    objectives: ['neutralization','civilian-protection','rescue','evacuation-escort'],
    escalationPath: ['panic-crush','enemy-reinforcement','structural-cascade'],
    combatFrame: ['civilian-presence-constraint','rescue-priorities','sightline-occlusion','cover-degradation'],
    enemyPressure: ['organized-militants'],
    dominantImagery: ['crowd','blood','urban'],
  },
  {
    id: 'terror-pipeline-sabotage',
    title: 'Pipeline Sabotage in Refinery Adjacent Town',
    concept: 'A demolition charge ruptures an oil pipeline running through a small refinery town, lake of fuel forming.',
    category: 'industrial-meltdown', scope: 'district', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 4,
    tags: ['oil','fire','industrial','urban','smoke'],
    timePressure: ['fuel reaching residential storm drains','any spark ignites the lake'],
    movementConstraints: ['ankle-deep oil','vapor cloud lowering','fences cutting evacuation routes'],
    collateral: ['elementary school three blocks downwind','retirement home next to drain outflow'],
    dynamicFactors: ['second charge planned downstream','militants withdrawing through marsh'],
    family: 'terrorist-sabotage', groundedness: 'grounded',
    objectives: ['cascade-interruption','evacuation-escort','neutralization','containment'],
    escalationPath: ['spreading-fire','toxic-spread','enemy-reinforcement'],
    combatFrame: ['environmental-weaponization','mobility-restriction','timed-pressure'],
    enemyPressure: ['organized-militants'],
    dominantImagery: ['oil','industrial','smoke','urban'],
  },
  {
    id: 'terror-airport-runway-attack',
    title: 'Armed Assault on Airport Tarmac',
    concept: 'Militants breach a perimeter fence and engage ground crews as a wide-body taxis to the gate.',
    category: 'transport-crisis', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 2, maxTier: 4,
    tags: ['urban','metal','aircraft','vehicle','smoke','gunfire'],
    timePressure: ['plane needs to abort or divert','ground crew exposed under wings'],
    movementConstraints: ['open tarmac, no cover','jet exhaust hazard','baggage trains as improvised cover'],
    collateral: ['three hundred passengers in cabin','tower controllers under fire'],
    dynamicFactors: ['MANPADS sighting reported','accomplice in cargo hold'],
    family: 'terrorist-sabotage', groundedness: 'grounded',
    objectives: ['neutralization','civilian-protection','rescue'],
    escalationPath: ['enemy-reinforcement','spreading-fire','structural-cascade'],
    combatFrame: ['cover-degradation','sightline-occlusion','civilian-presence-constraint'],
    enemyPressure: ['organized-militants'],
    dominantImagery: ['aircraft','metal','smoke','urban'],
  },

  // ── POLITICAL / CIVIL UNREST ─────────────────────────────────────────────
  {
    id: 'pol-capitol-storming',
    title: 'Capitol Building Stormed by Mob',
    concept: 'A coordinated mob breaches the legislature during a contested vote; lawmakers hide in basement chambers.',
    category: 'crowd-panic', scope: 'district', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['urban','crowd','rubble','glass','blood'],
    timePressure: ['lawmakers being hunted floor by floor','national guard hours away'],
    movementConstraints: ['rotunda packed shoulder-to-shoulder','barricaded chamber doors','staff hidden in cloakrooms'],
    collateral: ['legislators of both parties','press pool crouched in gallery'],
    dynamicFactors: ['armed faction within mob','officer shot in stairwell'],
    family: 'political-civil-unrest', groundedness: 'grounded',
    objectives: ['evacuation-escort','civilian-protection','defensive-hold','recon-in-chaos'],
    escalationPath: ['public-order-collapse','panic-crush','enemy-reinforcement'],
    combatFrame: ['civilian-presence-constraint','mobility-restriction','sightline-occlusion'],
    enemyPressure: ['panicked-mob','armed-criminals'],
    dominantImagery: ['urban','crowd','glass','blood'],
  },
  {
    id: 'pol-protest-turns-riot',
    title: 'Protest March Turning into Citywide Riot',
    concept: 'A peaceful demonstration is shattered by infiltrators throwing molotovs; police lines collapse.',
    category: 'crowd-panic', scope: 'city', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['urban','crowd','fire','smoke','glass'],
    timePressure: ['storefronts being torched in waves','journalists pinned at intersection'],
    movementConstraints: ['crowd current dragging individuals','tear-gas pockets','overturned cars'],
    collateral: ['injured protesters','shop owners defending storefronts','press pinned in alleys'],
    dynamicFactors: ['mounted police charge','secondary fire spreading to apartments'],
    family: 'political-civil-unrest', groundedness: 'grounded',
    objectives: ['rescue','civilian-protection','evacuation-escort'],
    escalationPath: ['public-order-collapse','spreading-fire','panic-crush'],
    combatFrame: ['civilian-presence-constraint','sightline-occlusion','mobility-restriction'],
    enemyPressure: ['panicked-mob','armed-criminals','corrupt-security'],
    dominantImagery: ['urban','crowd','fire','smoke'],
  },
  {
    id: 'pol-coup-night-broadcast',
    title: 'Military Coup Live on State Broadcast',
    concept: 'Tanks ring the state broadcaster as loyalist staff barricade the studio, civilians gathering in protest at the gates.',
    category: 'military-ordnance', scope: 'city', intensity: 'critical', rarity: 'grounded',
    minTier: 2, maxTier: 4,
    tags: ['urban','metal','crowd','smoke','vehicle'],
    timePressure: ['junta given thirty-minute deadline','generator fuel running low'],
    movementConstraints: ['armored cordon','rooftop snipers','crowd swarming armor'],
    collateral: ['civilian crowd at gates','journalists inside studio','child of news anchor on premises'],
    dynamicFactors: ['rival officers refusing orders','foreign embassy intervention'],
    family: 'political-civil-unrest', groundedness: 'grounded',
    objectives: ['defensive-hold','evacuation-escort','civilian-protection','recon-in-chaos'],
    escalationPath: ['enemy-reinforcement','public-order-collapse','communication-blackout'],
    combatFrame: ['cover-degradation','civilian-presence-constraint','sightline-occlusion'],
    enemyPressure: ['state-forces','panicked-mob'],
    dominantImagery: ['urban','metal','crowd'],
  },
  {
    id: 'pol-refugee-border-crush',
    title: 'Refugee Crush at Closing Border Crossing',
    concept: 'Tens of thousands surge against a border fence as it begins to close, soldiers losing line discipline.',
    category: 'crowd-panic', scope: 'regional', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['urban','crowd','dust','metal','wilderness'],
    timePressure: ['gate descending in minutes','people crushed against fence'],
    movementConstraints: ['compressed crowd in chute','razor wire above','vehicles abandoned across road'],
    collateral: ['families with infants','elderly losing footing','journalists embedded'],
    dynamicFactors: ['warning shots fired','vehicle ramming the gate'],
    family: 'political-civil-unrest', groundedness: 'grounded',
    objectives: ['rescue','civilian-protection','evacuation-escort'],
    escalationPath: ['panic-crush','public-order-collapse','enemy-reinforcement'],
    combatFrame: ['civilian-presence-constraint','rescue-priorities','mobility-restriction'],
    enemyPressure: ['state-forces','panicked-mob'],
    dominantImagery: ['crowd','dust','metal'],
  },
  {
    id: 'pol-embassy-siege',
    title: 'Embassy Siege Under Coordinated Mob Attack',
    concept: 'A mob breaches the outer compound of an embassy; staff retreat to the secure annex with shredders running.',
    category: 'crowd-panic', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 4,
    tags: ['urban','crowd','fire','smoke','glass'],
    timePressure: ['safe-room oxygen finite','classified material still in vault'],
    movementConstraints: ['barricaded corridors','smoke filling stairwells','vehicle barriers down'],
    collateral: ['ambassador and family','local staff trapped on lower floor'],
    dynamicFactors: ['second mob at rear gate','armed faction with RPGs'],
    family: 'political-civil-unrest', groundedness: 'grounded',
    objectives: ['defensive-hold','evacuation-escort','civilian-protection'],
    escalationPath: ['spreading-fire','enemy-reinforcement','public-order-collapse'],
    combatFrame: ['cover-degradation','civilian-presence-constraint','sightline-occlusion'],
    enemyPressure: ['panicked-mob','organized-militants'],
    dominantImagery: ['urban','crowd','fire','glass'],
  },

  // ── TRANSPORTATION CRISIS (granular gaps) ────────────────────────────────
  {
    id: 'trans-cargo-train-derail-urban',
    title: 'Hazmat Cargo Train Derailed in Dense Neighborhood',
    concept: 'A freight train carrying chlorine cars jumps the rails in a residential neighborhood at 3 AM.',
    category: 'transport-crisis', scope: 'district', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 4,
    tags: ['urban','rail','metal','chemical','smoke','toxin'],
    timePressure: ['venting chlorine cloud spreading','tank seams failing'],
    movementConstraints: ['twisted rolling stock blocking streets','toxic plume defining no-go zone','collapsed overpass'],
    collateral: ['sleeping families three blocks downwind','hospital one mile away'],
    dynamicFactors: ['second tank rupture','gas-fed fire from torn fuel car'],
    family: 'transportation-crisis', groundedness: 'grounded',
    objectives: ['evacuation-escort','containment','rescue','cascade-interruption'],
    escalationPath: ['toxic-spread','spreading-fire','panic-crush'],
    combatFrame: ['shifting-hazard-zones','mobility-restriction','timed-pressure'],
    enemyPressure: ['no-enemy','panicked-mob'],
    dominantImagery: ['rail','metal','chemical','toxin','smoke'],
  },
  {
    id: 'trans-highway-pile-up-fog',
    title: 'Hundred-Vehicle Pile-up in Freeway Fog Bank',
    concept: 'A wall of fog on an interstate triggers a chain-reaction crash with fuel fires and trapped commuters.',
    category: 'transport-crisis', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['vehicle','fire','smoke','metal','urban'],
    timePressure: ['additional cars still arriving at speed','tanker fuel pooling under wreckage'],
    movementConstraints: ['stacked wreckage','near-zero visibility','crushed bodies inside cabins'],
    collateral: ['families in minivans','school bus near front of pile-up'],
    dynamicFactors: ['secondary explosion','arriving traffic adding to chain'],
    family: 'transportation-crisis', groundedness: 'grounded',
    objectives: ['rescue','extraction','civilian-protection','containment'],
    escalationPath: ['spreading-fire','enemy-reinforcement','panic-crush'],
    combatFrame: ['mobility-restriction','rescue-priorities','sightline-occlusion','timed-pressure'],
    enemyPressure: ['no-enemy'],
    dominantImagery: ['vehicle','fire','smoke','metal'],
  },
  {
    id: 'trans-airliner-emergency-landing',
    title: 'Wide-Body Emergency Landing on Suburban Highway',
    concept: 'A crippled airliner brings itself down on a suburban arterial road, breaking apart on impact.',
    category: 'transport-crisis', scope: 'district', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 4,
    tags: ['aircraft','fire','metal','urban','rubble','smoke'],
    timePressure: ['fuselage fire spreading toward fuel tanks','passengers trapped behind buckled exits'],
    movementConstraints: ['debris field across four blocks','sheared fuselage sections','live electrical lines on aircraft'],
    collateral: ['three hundred passengers','suburban homes pierced by debris'],
    dynamicFactors: ['cargo containing lithium batteries','fuel running into storm drains'],
    family: 'transportation-crisis', groundedness: 'grounded',
    objectives: ['rescue','evacuation-escort','civilian-protection','containment'],
    escalationPath: ['spreading-fire','structural-cascade','panic-crush'],
    combatFrame: ['rescue-priorities','timed-pressure','mobility-restriction'],
    enemyPressure: ['no-enemy'],
    dominantImagery: ['aircraft','fire','metal','smoke','urban'],
  },
  {
    id: 'trans-ferry-storm-capsize',
    title: 'Ferry Capsizing in Storm Surge',
    concept: 'An overloaded passenger ferry begins to capsize in heavy seas miles from any harbor.',
    category: 'maritime-deepwater', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['water','wind','storm','vehicle','metal','crowd'],
    timePressure: ['list increasing each minute','lifeboats jammed by tilt'],
    movementConstraints: ['sloping decks','flooded car deck','panicked crowd surging upward'],
    collateral: ['eight hundred passengers','families separated below decks'],
    dynamicFactors: ['rogue wave inbound','engine room fire'],
    family: 'transportation-crisis', groundedness: 'grounded',
    objectives: ['rescue','evacuation-escort','civilian-protection'],
    escalationPath: ['flood-progression','spreading-fire','panic-crush'],
    combatFrame: ['mobility-restriction','rescue-priorities','changing-terrain'],
    enemyPressure: ['no-enemy','panicked-mob'],
    dominantImagery: ['water','wind','storm','metal','crowd'],
  },
  {
    id: 'trans-subway-derail-tunnel',
    title: 'Subway Train Derailment Mid-Tunnel',
    concept: 'A rush-hour train derails in a curved tunnel section, lead car jammed against the wall.',
    category: 'transport-crisis', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['tunnel','metal','smoke','crowd','urban','dust'],
    timePressure: ['third rail still energized','smoke filling tunnel'],
    movementConstraints: ['crushed front car','narrow walking gap beside rails','no light beyond emergency strips'],
    collateral: ['hundreds of commuters','wheelchair user trapped'],
    dynamicFactors: ['second train approaching from behind','tunnel ventilation failure'],
    family: 'transportation-crisis', groundedness: 'grounded',
    objectives: ['rescue','extraction','civilian-protection','cascade-interruption'],
    escalationPath: ['spreading-fire','panic-crush','communication-blackout'],
    combatFrame: ['mobility-restriction','sightline-occlusion','rescue-priorities'],
    enemyPressure: ['no-enemy','panicked-mob'],
    dominantImagery: ['tunnel','metal','smoke','crowd','urban'],
  },
  {
    id: 'trans-cruise-ship-fire',
    title: 'Engine Room Fire on Cruise Liner Mid-Ocean',
    concept: 'A galley fire spreads to engine spaces of a packed cruise ship, propulsion lost, drifting toward reef.',
    category: 'maritime-deepwater', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['water','fire','smoke','metal','crowd','vehicle'],
    timePressure: ['drift to reef in three hours','passengers fleeing to upper decks'],
    movementConstraints: ['smoke-filled corridors','sealed fire doors','overcrowded muster stations'],
    collateral: ['four thousand passengers and crew','infirmary patients on lower deck'],
    dynamicFactors: ['fuel-bunker breach','helicopter evacuation in heavy swell'],
    family: 'transportation-crisis', groundedness: 'grounded',
    objectives: ['evacuation-escort','rescue','containment'],
    escalationPath: ['spreading-fire','structural-cascade','panic-crush'],
    combatFrame: ['mobility-restriction','rescue-priorities','sightline-occlusion'],
    enemyPressure: ['no-enemy','panicked-mob'],
    dominantImagery: ['water','fire','smoke','metal'],
  },
  {
    id: 'trans-tunnel-collapse-traffic',
    title: 'Highway Tunnel Collapse Trapping Hundreds of Vehicles',
    concept: 'A section of a major undersea or mountain road tunnel collapses mid-rush hour, sealing both ends.',
    category: 'urban-collapse', scope: 'district', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 4,
    tags: ['tunnel','rubble','vehicle','smoke','metal'],
    timePressure: ['ventilation failed, CO climbing','water seepage on undersea section'],
    movementConstraints: ['crushed cars','rubble piles','no light beyond car headlamps'],
    collateral: ['hundreds of motorists','tour bus filled with elderly'],
    dynamicFactors: ['secondary collapse','fuel-tanker fire'],
    family: 'urban-infrastructure-failure', groundedness: 'grounded',
    objectives: ['rescue','extraction','civilian-protection'],
    escalationPath: ['structural-cascade','spreading-fire','flood-progression','panic-crush'],
    combatFrame: ['mobility-restriction','sightline-occlusion','rescue-priorities','scarce-resources'],
    enemyPressure: ['no-enemy'],
    dominantImagery: ['tunnel','rubble','vehicle','smoke'],
  },
  {
    id: 'trans-port-container-collapse',
    title: 'Stack Collapse in Active Container Port',
    concept: 'A wind gust topples a forty-foot stack of containers across a working terminal, crushing equipment and crews.',
    category: 'transport-crisis', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['industrial','metal','rubble','wind','dust'],
    timePressure: ['adjacent stacks unstable','workers pinned beneath cans'],
    movementConstraints: ['narrow channels between stacks','fallen reefer cans leaking refrigerant','cranes swaying overhead'],
    collateral: ['stevedores in chokepoints','crane operator stranded forty meters up'],
    dynamicFactors: ['hazmat container ruptured','crane base undermined'],
    family: 'transportation-crisis', groundedness: 'grounded',
    objectives: ['rescue','extraction','containment'],
    escalationPath: ['structural-cascade','toxic-spread','enemy-reinforcement'],
    combatFrame: ['mobility-restriction','verticality-collapse','rescue-priorities'],
    enemyPressure: ['no-enemy'],
    dominantImagery: ['industrial','metal','rubble','dust'],
  },

  // ── PUBLIC SYSTEMS FAILURE ───────────────────────────────────────────────
  {
    id: 'pub-hospital-power-loss',
    title: 'Hospital Backup Power Failure During Mass Casualty Intake',
    concept: 'A trauma center loses primary and backup power as ambulances queue with mass-casualty arrivals.',
    category: 'infrastructure-failure', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['urban','electric','blood','metal','crowd'],
    timePressure: ['ventilator patients on bag-masks','OR cases mid-procedure'],
    movementConstraints: ['dark corridors','elevators stuck between floors','triage in lobby'],
    collateral: ['ICU patients','newborns in NICU','surgical patients on tables'],
    dynamicFactors: ['fire on fourth floor adding casualties','generator fuel contaminated'],
    family: 'public-systems-failure', groundedness: 'grounded',
    objectives: ['rescue','civilian-protection','cascade-interruption','infrastructure-preservation'],
    escalationPath: ['communication-blackout','panic-crush','public-order-collapse'],
    combatFrame: ['scarce-resources','rescue-priorities','sightline-occlusion','civilian-presence-constraint'],
    enemyPressure: ['no-enemy','panicked-mob'],
    dominantImagery: ['urban','electric','blood'],
  },
  {
    id: 'pub-911-dispatch-cyber',
    title: 'Citywide 911 Dispatch Knocked Out by Cyberattack',
    concept: 'Emergency dispatch and police radios go silent during a mass-incident night; field officers blind.',
    category: 'infrastructure-failure', scope: 'city', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['urban','electric','crowd'],
    timePressure: ['ongoing assaults with no responders','window before secondary attacks'],
    movementConstraints: ['officers using personal phones','foot-runners between precincts','traffic gridlocked'],
    collateral: ['active medical emergencies citywide','isolated officers under fire'],
    dynamicFactors: ['ransom demand to restore service','copycat attackers exploiting silence'],
    family: 'public-systems-failure', groundedness: 'grounded',
    objectives: ['cascade-interruption','civilian-protection','recon-in-chaos','infrastructure-preservation'],
    escalationPath: ['communication-blackout','public-order-collapse','enemy-reinforcement'],
    combatFrame: ['scarce-resources','sightline-occlusion','unstable-objectives'],
    enemyPressure: ['no-enemy','armed-criminals'],
    dominantImagery: ['urban','electric'],
  },
  {
    id: 'pub-water-main-burst-downtown',
    title: 'Twin Water-Main Burst Flooding Downtown',
    concept: 'A century-old main and its parallel rupture beneath a packed financial district at lunch hour.',
    category: 'infrastructure-failure', scope: 'district', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['water','urban','rubble','flood','metal'],
    timePressure: ['street collapsing into voids','subway entrances flooding'],
    movementConstraints: ['waist-deep current down sidewalks','sinkholes opening underfoot','manhole covers ejected'],
    collateral: ['lunchtime crowds','subway riders below','basement-level shops'],
    dynamicFactors: ['second main blowing on parallel street','electrical short in flooded substation'],
    family: 'public-systems-failure', groundedness: 'grounded',
    objectives: ['rescue','evacuation-escort','cascade-interruption','infrastructure-preservation'],
    escalationPath: ['flood-progression','structural-cascade','public-order-collapse'],
    combatFrame: ['changing-terrain','mobility-restriction','rescue-priorities'],
    enemyPressure: ['no-enemy','panicked-mob'],
    dominantImagery: ['water','urban','rubble','flood'],
  },
  {
    id: 'pub-natural-gas-leak-market',
    title: 'Natural Gas Main Rupture Under Crowded Street Market',
    concept: 'A street-market crowd unknowingly stands above a leaking gas main feeding into the storm drains.',
    category: 'infrastructure-failure', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['urban','crowd','smoke','fire','vehicle'],
    timePressure: ['gas pocket near ignition source','first sparks already arcing'],
    movementConstraints: ['densely packed market stalls','tangled tarps and cables','vehicle traffic on perimeter'],
    collateral: ['hundreds of shoppers','food vendors with open flames'],
    dynamicFactors: ['cigarette butt landing in drain','vehicle backfire near manhole'],
    family: 'public-systems-failure', groundedness: 'grounded',
    objectives: ['evacuation-escort','cascade-interruption','civilian-protection'],
    escalationPath: ['spreading-fire','panic-crush','structural-cascade'],
    combatFrame: ['civilian-presence-constraint','timed-pressure','mobility-restriction'],
    enemyPressure: ['no-enemy','panicked-mob'],
    dominantImagery: ['urban','crowd','smoke'],
  },
  {
    id: 'pub-airport-tower-blackout',
    title: 'Air-Traffic Tower Total Blackout',
    concept: 'A regional airport loses tower power and radar; six aircraft on approach, two missed already.',
    category: 'infrastructure-failure', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['aircraft','urban','electric','metal'],
    timePressure: ['aircraft fuel windows shrinking','no separation control'],
    movementConstraints: ['stairs to backup tower','equipment in dark','runway lights dark'],
    collateral: ['hundreds aboard each aircraft','ground crews in motion'],
    dynamicFactors: ['weather closing in','small aircraft straying into approach'],
    family: 'public-systems-failure', groundedness: 'grounded',
    objectives: ['cascade-interruption','infrastructure-preservation','rescue'],
    escalationPath: ['communication-blackout','structural-cascade','panic-crush'],
    combatFrame: ['scarce-resources','timed-pressure','sightline-occlusion'],
    enemyPressure: ['no-enemy'],
    dominantImagery: ['aircraft','electric','urban'],
  },
  {
    id: 'pub-sewer-methane-explosion',
    title: 'Methane Buildup Igniting Beneath City Block',
    concept: 'A sewer methane buildup ignites and travels under a residential block, popping manholes and lifting pavement.',
    category: 'infrastructure-failure', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['urban','fire','smoke','rubble','metal'],
    timePressure: ['secondary pockets cooking off','gas line above leak threatened'],
    movementConstraints: ['ejected manhole covers as projectiles','heaved pavement','smoke-filled basements'],
    collateral: ['residents in basements','schoolyard above main sewer trunk'],
    dynamicFactors: ['water main rupture from heat','transformer arc above'],
    family: 'public-systems-failure', groundedness: 'grounded',
    objectives: ['evacuation-escort','cascade-interruption','rescue'],
    escalationPath: ['spreading-fire','structural-cascade','panic-crush'],
    combatFrame: ['timed-pressure','shifting-hazard-zones','mobility-restriction'],
    enemyPressure: ['no-enemy'],
    dominantImagery: ['urban','fire','smoke','rubble'],
  },

  // ── BIOLOGICAL HAZARD (grounded) ─────────────────────────────────────────
  {
    id: 'bio-rural-water-contamination',
    title: 'E. coli Outbreak in Rural Town Water Supply',
    concept: 'A municipal well is contaminated with farm runoff; entire town presenting at understaffed clinic.',
    category: 'biological-outbreak', scope: 'district', intensity: 'rising', rarity: 'grounded',
    minTier: 1, maxTier: 2,
    tags: ['water','toxin','urban','wilderness'],
    timePressure: ['vulnerable patients deteriorating','ambulance turnaround time too long'],
    movementConstraints: ['clinic overwhelmed','families bedridden in homes','dirt roads to outlying farms'],
    collateral: ['children and elderly worst hit','dialysis patients in trouble'],
    dynamicFactors: ['second source still leaking','drug shortage at clinic'],
    family: 'biological-hazard', groundedness: 'grounded',
    objectives: ['rescue','containment','civilian-protection','recon-in-chaos'],
    escalationPath: ['toxic-spread','resource-exhaustion','panic-crush'],
    combatFrame: ['scarce-resources','rescue-priorities','civilian-presence-constraint'],
    enemyPressure: ['no-enemy'],
    dominantImagery: ['water','toxin','urban'],
  },
  {
    id: 'bio-quarantine-breach-airport',
    title: 'Quarantine Breach at International Arrivals',
    concept: 'A passenger with a hemorrhagic illness collapses in baggage claim, contaminating a packed terminal.',
    category: 'biological-outbreak', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['urban','toxin','crowd','blood','metal'],
    timePressure: ['airport about to be sealed','passengers dispersing through transit'],
    movementConstraints: ['plastic-wrapped quarantine zone','crowd panic at perimeter','baggage carousels still moving'],
    collateral: ['hundreds of arrivals','staff with no PPE'],
    dynamicFactors: ['second symptomatic passenger boarding shuttle','press inside the secure zone'],
    family: 'biological-hazard', groundedness: 'grounded',
    objectives: ['containment','civilian-protection','rescue','recon-in-chaos'],
    escalationPath: ['toxic-spread','panic-crush','public-order-collapse'],
    combatFrame: ['civilian-presence-constraint','scarce-resources','mobility-restriction'],
    enemyPressure: ['no-enemy','panicked-mob'],
    dominantImagery: ['urban','toxin','crowd','blood'],
  },
  {
    id: 'bio-livestock-zoonotic-jump',
    title: 'Zoonotic Outbreak in Livestock Auction',
    concept: 'A novel pathogen jumps from livestock to handlers at a regional auction filled with farmers and traders.',
    category: 'biological-outbreak', scope: 'district', intensity: 'rising', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['urban','toxin','wilderness','crowd','dust'],
    timePressure: ['sick handlers dispersing home','animals being trucked across state lines'],
    movementConstraints: ['mud and manure underfoot','livestock pens narrowing aisles','no biosecurity'],
    collateral: ['farmers from twelve counties','child livestock-show participants'],
    dynamicFactors: ['veterinary team exposed','contaminated trucks already departed'],
    family: 'biological-hazard', groundedness: 'grounded',
    objectives: ['containment','recon-in-chaos','civilian-protection'],
    escalationPath: ['toxic-spread','public-order-collapse','resource-exhaustion'],
    combatFrame: ['civilian-presence-constraint','scarce-resources','sightline-occlusion'],
    enemyPressure: ['no-enemy'],
    dominantImagery: ['toxin','wilderness','crowd','dust'],
  },

  // ── TECHNOLOGICAL MALFUNCTION (grounded) ─────────────────────────────────
  {
    id: 'tech-traffic-signal-cyber',
    title: 'Coordinated Traffic-Signal Hack Across City',
    concept: 'Every traffic signal in a downtown core flashes green simultaneously during evening rush.',
    category: 'infrastructure-failure', scope: 'city', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['urban','vehicle','metal','crowd','electric'],
    timePressure: ['casualties accumulating per minute','signals not responding to manual override'],
    movementConstraints: ['gridlocked intersections','crashed vehicles','panicked drivers fleeing on foot'],
    collateral: ['drivers and pedestrians at every intersection','school buses caught in junctions'],
    dynamicFactors: ['ransomware demand','attempted second-stage attack on rail crossings'],
    family: 'technological-malfunction', groundedness: 'grounded',
    objectives: ['cascade-interruption','rescue','civilian-protection','infrastructure-preservation'],
    escalationPath: ['communication-blackout','public-order-collapse','enemy-reinforcement'],
    combatFrame: ['mobility-restriction','sightline-occlusion','rescue-priorities'],
    enemyPressure: ['no-enemy'],
    dominantImagery: ['urban','vehicle','electric'],
  },
  {
    id: 'tech-warehouse-robotics-runaway',
    title: 'Warehouse Robotics Runaway During Night Shift',
    concept: 'Automated picker arms in a giant fulfillment center go haywire, threatening third-shift staff still inside.',
    category: 'mechanical-runaway', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['industrial','metal','electric','dust'],
    timePressure: ['workers pinned in aisles','arms reaching higher loads'],
    movementConstraints: ['mile-long racks','overhead conveyors swinging','cages locking automatically'],
    collateral: ['skeleton night crew','cleaners with no comms'],
    dynamicFactors: ['fire from short-circuit on lift','sprinkler heads triggered'],
    family: 'technological-malfunction', groundedness: 'grounded',
    objectives: ['cascade-interruption','rescue','extraction'],
    escalationPath: ['containment-rupture','spreading-fire','communication-blackout'],
    combatFrame: ['environmental-weaponization','mobility-restriction','sightline-occlusion'],
    enemyPressure: ['rogue-machines'],
    dominantImagery: ['industrial','metal','electric'],
  },
  {
    id: 'tech-self-driving-fleet-loop',
    title: 'Autonomous Taxi Fleet Stuck in Hostile Loop',
    concept: 'A bug puts a city\'s autonomous-taxi fleet into an aggressive loop, ramming pedestrians and each other.',
    category: 'mechanical-runaway', scope: 'district', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['urban','vehicle','metal','crowd','electric'],
    timePressure: ['fleet behavior synchronizing','manual kill-switches not responding'],
    movementConstraints: ['unpredictable vehicle paths','pedestrian crowds fleeing','jammed sidewalks'],
    collateral: ['rideshare passengers locked in','pedestrians on busy sidewalks'],
    dynamicFactors: ['paid hacker demanding crypto','copycat fleet operator affected'],
    family: 'technological-malfunction', groundedness: 'grounded',
    objectives: ['cascade-interruption','civilian-protection','rescue'],
    escalationPath: ['public-order-collapse','panic-crush','enemy-reinforcement'],
    combatFrame: ['mobility-restriction','civilian-presence-constraint','rescue-priorities'],
    enemyPressure: ['rogue-machines'],
    dominantImagery: ['urban','vehicle','metal','crowd'],
  },

  // ── MASS PANIC EVENT ─────────────────────────────────────────────────────
  {
    id: 'panic-stadium-stampede',
    title: 'Stampede at Festival Main Stage',
    concept: 'A false alarm at a sold-out music festival triggers a stampede toward narrow exits.',
    category: 'crowd-panic', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 2,
    tags: ['crowd','urban','dust','metal','blood'],
    timePressure: ['compression deaths in chokepoints','more crowd surging from main stage'],
    movementConstraints: ['immovable human current','fallen victims becoming hazards','barricades funneling crowd'],
    collateral: ['tens of thousands of festival-goers','children on shoulders'],
    dynamicFactors: ['secondary alarm at opposite gate','gate failing to open'],
    family: 'mass-panic-event', groundedness: 'grounded',
    objectives: ['rescue','civilian-protection','evacuation-escort'],
    escalationPath: ['panic-crush','public-order-collapse','enemy-reinforcement'],
    combatFrame: ['civilian-presence-constraint','rescue-priorities','mobility-restriction'],
    enemyPressure: ['panicked-mob'],
    dominantImagery: ['crowd','urban','dust','blood'],
  },
  {
    id: 'panic-school-evacuation-bomb-call',
    title: 'School Evacuation Under Bomb Threat',
    concept: 'A high school of two thousand evacuates under a credible bomb threat with the device location unknown.',
    category: 'crowd-panic', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 2,
    tags: ['urban','crowd','metal','rubble'],
    timePressure: ['caller gave fifteen-minute deadline','disabled students still in upper floors'],
    movementConstraints: ['staircase bottlenecks','locker-lined hallways','outdoor muster zone exposed'],
    collateral: ['students with mobility issues','infants in onsite daycare'],
    dynamicFactors: ['second threat to muster zone','copycat caller'],
    family: 'mass-panic-event', groundedness: 'grounded',
    objectives: ['evacuation-escort','recon-in-chaos','civilian-protection'],
    escalationPath: ['panic-crush','enemy-reinforcement','communication-blackout'],
    combatFrame: ['civilian-presence-constraint','timed-pressure','rescue-priorities'],
    enemyPressure: ['no-enemy','panicked-mob'],
    dominantImagery: ['urban','crowd','metal'],
  },

  // ── SURVIVAL BREAKDOWN ───────────────────────────────────────────────────
  {
    id: 'surv-week-three-of-blackout',
    title: 'Week Three of Regional Blackout',
    concept: 'A regional grid has been down for three weeks; food and water systems collapsing, vigilantism rising.',
    category: 'wilderness-survival', scope: 'regional', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['urban','wilderness','crowd','dust','blood'],
    timePressure: ['water reserves down to days','medical supply caches running out'],
    movementConstraints: ['barricaded streets','armed neighborhood watch','unpredictable curfews'],
    collateral: ['elderly without medication','infants needing formula','dialysis patients'],
    dynamicFactors: ['gangs forming around water sources','militia checkpoints'],
    family: 'survival-breakdown', groundedness: 'grounded',
    objectives: ['rescue','civilian-protection','recon-in-chaos','extraction'],
    escalationPath: ['resource-exhaustion','public-order-collapse','enemy-reinforcement'],
    combatFrame: ['scarce-resources','sightline-occlusion','mobility-restriction'],
    enemyPressure: ['armed-criminals','panicked-mob','corrupt-security'],
    dominantImagery: ['urban','crowd','blood','wilderness'],
  },
  {
    id: 'surv-stranded-arctic-station',
    title: 'Stranded Crew at Arctic Research Station',
    concept: 'Resupply window has closed for the winter and the heating system is failing at a remote arctic outpost.',
    category: 'wilderness-survival', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['ice','wind','wilderness','metal','snow'],
    timePressure: ['cabin temperatures dropping hourly','medical patient deteriorating'],
    movementConstraints: ['polar dark','whiteout conditions outdoors','frozen door seals'],
    collateral: ['twelve scientists','one with appendicitis'],
    dynamicFactors: ['fuel line freeze','polar bear sighting nearby'],
    family: 'survival-breakdown', groundedness: 'grounded',
    objectives: ['survival-under-collapse','rescue','extraction'],
    escalationPath: ['weather-deterioration','resource-exhaustion','communication-blackout'],
    combatFrame: ['scarce-resources','mobility-restriction','sightline-occlusion'],
    enemyPressure: ['no-enemy','hostile-wildlife'],
    dominantImagery: ['ice','wind','snow','wilderness'],
  },
  {
    id: 'surv-desert-bus-breakdown',
    title: 'Desert Bus Breakdown Off Marked Route',
    concept: 'A tour bus breaks down hours off the marked route in midday desert heat with limited water.',
    category: 'wilderness-survival', scope: 'local', intensity: 'rising', rarity: 'grounded',
    minTier: 1, maxTier: 2,
    tags: ['wilderness','dust','vehicle','metal'],
    timePressure: ['heat stroke onset within hours','water rations dwindling'],
    movementConstraints: ['no shade beyond bus','soft sand off-road','phone signal dead'],
    collateral: ['forty passengers including elderly','child with asthma'],
    dynamicFactors: ['sandstorm forecast','engine fire risk if restarted'],
    family: 'survival-breakdown', groundedness: 'grounded',
    objectives: ['survival-under-collapse','evacuation-escort','rescue'],
    escalationPath: ['weather-deterioration','resource-exhaustion'],
    combatFrame: ['scarce-resources','mobility-restriction','timed-pressure'],
    enemyPressure: ['no-enemy'],
    dominantImagery: ['wilderness','dust','vehicle'],
  },

  // ── MILITARY CONFLICT (grounded, non-cosmic) ─────────────────────────────
  {
    id: 'mil-evac-foreign-embassy',
    title: 'Forced Evacuation of Foreign Embassy in Falling Capital',
    concept: 'A capital is falling to insurgents; the embassy must be cleared and locals evacuated within hours.',
    category: 'military-ordnance', scope: 'city', intensity: 'critical', rarity: 'grounded',
    minTier: 2, maxTier: 4,
    tags: ['urban','smoke','crowd','metal','blood'],
    timePressure: ['runway open for hours','convoy windows narrowing'],
    movementConstraints: ['choked streets','rooftop sniper threats','barricaded routes'],
    collateral: ['embassy staff','local employees','at-risk allies'],
    dynamicFactors: ['insurgent vanguard arriving early','helicopters landing on roof'],
    family: 'military-conflict', groundedness: 'grounded',
    objectives: ['extraction','evacuation-escort','defensive-hold','civilian-protection'],
    escalationPath: ['enemy-reinforcement','spreading-fire','public-order-collapse'],
    combatFrame: ['cover-degradation','sightline-occlusion','civilian-presence-constraint'],
    enemyPressure: ['organized-militants','state-forces'],
    dominantImagery: ['urban','smoke','crowd','blood'],
  },
  {
    id: 'mil-convoy-ied-ambush',
    title: 'Convoy IED Ambush on Mountain Road',
    concept: 'A relief convoy is hit by chained IEDs on a switchback mountain road, ambushers in the rocks above.',
    category: 'military-ordnance', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 2, maxTier: 4,
    tags: ['wilderness','rock','vehicle','smoke','blood','metal'],
    timePressure: ['second pass of the ambush','wounded on lead vehicle'],
    movementConstraints: ['cliff on one side, drop on the other','vehicle wreckage in the road'],
    collateral: ['relief workers in trail vehicle','wounded driver pinned'],
    dynamicFactors: ['mortar fire from ridge','reinforcements minutes out'],
    family: 'military-conflict', groundedness: 'grounded',
    objectives: ['extraction','rescue','defensive-hold','recon-in-chaos'],
    escalationPath: ['enemy-reinforcement','spreading-fire','communication-blackout'],
    combatFrame: ['cover-degradation','sightline-occlusion','mobility-restriction'],
    enemyPressure: ['organized-militants'],
    dominantImagery: ['wilderness','rock','vehicle','smoke','blood'],
  },
  {
    id: 'mil-naval-base-saboteur',
    title: 'Saboteur Inside Active Naval Base',
    concept: 'An insider has planted devices on moored vessels and shore facilities at a working naval base.',
    category: 'military-ordnance', scope: 'district', intensity: 'critical', rarity: 'grounded',
    minTier: 2, maxTier: 4,
    tags: ['water','metal','industrial','smoke','vehicle'],
    timePressure: ['carrier scheduled to depart','dry-dock crew at work'],
    movementConstraints: ['restricted-area chokepoints','dock pilings as cover','cranes overhead'],
    collateral: ['ships\' crews','dry-dock contractors'],
    dynamicFactors: ['second saboteur in CIC','attack timed with broader op'],
    family: 'military-conflict', groundedness: 'grounded',
    objectives: ['neutralization','cascade-interruption','infrastructure-preservation'],
    escalationPath: ['containment-rupture','spreading-fire','enemy-reinforcement'],
    combatFrame: ['sightline-occlusion','timed-pressure','environmental-weaponization'],
    enemyPressure: ['organized-militants'],
    dominantImagery: ['water','metal','industrial','smoke'],
  },

  // ── ENVIRONMENTAL COLLAPSE (grounded) ────────────────────────────────────
  {
    id: 'env-heatdome-megacity',
    title: 'Heat Dome Killing Hundreds in Megacity',
    concept: 'A multi-day heat dome over a high-density city pushes power and water systems past failure.',
    category: 'atmospheric-storm', scope: 'city', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['urban','crowd','dust','electric'],
    timePressure: ['cooling centers overflowing','rolling blackouts spreading'],
    movementConstraints: ['streets too hot to cross safely','dead transit','elevators stuck'],
    collateral: ['elderly in walk-up apartments','homeless on overheating pavement','asthmatic children'],
    dynamicFactors: ['water rationing failing','riot at one cooling center'],
    family: 'environmental-collapse', groundedness: 'grounded',
    objectives: ['rescue','evacuation-escort','civilian-protection','infrastructure-preservation'],
    escalationPath: ['weather-deterioration','resource-exhaustion','public-order-collapse'],
    combatFrame: ['scarce-resources','mobility-restriction','rescue-priorities'],
    enemyPressure: ['no-enemy','panicked-mob'],
    dominantImagery: ['urban','crowd','dust'],
  },
  {
    id: 'env-toxic-algal-bloom',
    title: 'Toxic Algal Bloom Closing Coastal Resort',
    concept: 'A red-tide bloom kills marine life and causes mass respiratory casualties along a packed beach resort strip.',
    category: 'biological-outbreak', scope: 'district', intensity: 'rising', rarity: 'grounded',
    minTier: 1, maxTier: 2,
    tags: ['water','toxin','urban','crowd','dust'],
    timePressure: ['onshore wind pushing aerosol inland','beach crowd not yet evacuated'],
    movementConstraints: ['boardwalk congestion','medical tents overrun','no PPE'],
    collateral: ['vacationing families','asthmatic children','dolphins washing ashore'],
    dynamicFactors: ['second bloom along coast','water-treatment intake threatened'],
    family: 'environmental-collapse', groundedness: 'grounded',
    objectives: ['evacuation-escort','civilian-protection','containment'],
    escalationPath: ['toxic-spread','weather-deterioration','public-order-collapse'],
    combatFrame: ['shifting-hazard-zones','rescue-priorities','scarce-resources'],
    enemyPressure: ['no-enemy'],
    dominantImagery: ['water','toxin','urban','crowd'],
  },
];
