/**
 * Emergency Blueprints
 *
 * A catalog of 120+ base danger situations spanning intensity, scope, scale,
 * environment, and threat type. Each blueprint is a *seed* — the composer
 * layers modular twists on top (civilian density, time pressure mechanic,
 * dynamic factors, mood) so two generations from the same blueprint still
 * feel distinct.
 *
 * Shared between the in-engine ScenarioBrain (PvE/EvE) and the
 * `generate-emergency-location` edge function (battle scene seeding) so all
 * emergency content draws from the same diverse pool.
 *
 * Pure data — no runtime deps so it loads in Deno and the browser.
 */

export type DangerCategory =
  | 'natural-disaster'
  | 'urban-collapse'
  | 'transport-crisis'
  | 'industrial-meltdown'
  | 'infrastructure-failure'
  | 'biological-outbreak'
  | 'fire-conflagration'
  | 'water-flooding'
  | 'atmospheric-storm'
  | 'seismic-tectonic'
  | 'volcanic-thermal'
  | 'cryogenic-arctic'
  | 'chemical-radiological'
  | 'energy-overload'
  | 'mechanical-runaway'
  | 'orbital-aerospace'
  | 'maritime-deepwater'
  | 'subterranean-cavern'
  | 'wilderness-survival'
  | 'crowd-panic'
  | 'military-ordnance'
  | 'sci-fi-advanced'
  | 'planetary-extreme'
  | 'mythic-cosmic';

export type DangerScope = 'local' | 'district' | 'city' | 'regional' | 'continental' | 'planetary' | 'cosmic';
export type DangerIntensity = 'simmering' | 'rising' | 'critical' | 'cataclysmic';
export type RarityTier = 'grounded' | 'advanced' | 'extreme' | 'mythic';
export type SurvivabilityFloor = 1 | 2 | 3 | 4 | 5;

export interface EmergencyBlueprint {
  /** Stable id — used for memory dedup and analytics */
  id: string;
  /** Short evocative title — composer can rename, but this seeds it */
  title: string;
  /** One-line concept the AI should expand */
  concept: string;
  category: DangerCategory;
  scope: DangerScope;
  intensity: DangerIntensity;
  rarity: RarityTier;
  /** Minimum tier this scenario makes narrative sense for (1 = anyone) */
  minTier: SurvivabilityFloor;
  /** Maximum tier where it still feels *threatening* (5 = always) */
  maxTier: SurvivabilityFloor;
  /** Default movement / hazard tags surfaced to the engine */
  tags: string[];
  /** Specific time-pressure mechanics that fit this blueprint */
  timePressure: string[];
  /** Movement / terrain constraints the blueprint imposes */
  movementConstraints: string[];
  /** Civilian or collateral hooks (empty = uninhabited setting) */
  collateral: string[];
  /** Suggested dynamic escalation factors */
  dynamicFactors: string[];
  /** Planet/location compatibility — empty array = anywhere */
  planetAffinity?: string[]; // e.g. ['earth-like', 'desert', 'ocean', 'space']
}

export const EMERGENCY_BLUEPRINTS: EmergencyBlueprint[] = [
  {
    id: 'nat-flash-flood-canyon',
    title: 'Flash Flood in Slot Canyon',
    concept: 'A wall of muddy water rips down a narrow slot canyon trapping hikers between sheer rock walls.',
    category: 'natural-disaster', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['water','flood','canyon','rubble','rock','wilderness'],
    timePressure: ['water level rising one meter per ten seconds','escape ledges submerging in sequence'],
    movementConstraints: ['wading through chest-high current','slick canyon walls','no horizontal exits'],
    collateral: ['stranded hiking group','child clinging to driftwood'],
    dynamicFactors: ['second surge from upstream','log jam shifting downstream'],
  },
  {
    id: 'nat-wildfire-firestorm',
    title: 'Firestorm Crowning Through Pine Forest',
    concept: 'A wind-driven wildfire jumps the canopy creating a self-feeding firestorm that traps a fire crew.',
    category: 'fire-conflagration', scope: 'regional', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 4,
    tags: ['fire','smoke','wilderness','wind'],
    timePressure: ['fire front advancing fifty meters per minute','oxygen depletion in low pockets'],
    movementConstraints: ['dense smoke reducing visibility to arm length','burning deadfall blocking trails'],
    collateral: ['trapped fire crew','wildlife stampede','remote cabin community'],
    dynamicFactors: ['ember storm igniting fresh fronts','wind reversal','propane tank cookoff'],
  },
  {
    id: 'nat-tornado-on-town',
    title: 'EF-5 Tornado Bearing Down on Main Street',
    concept: 'A wedge tornado scours a suburban downtown, throwing vehicles like confetti.',
    category: 'atmospheric-storm', scope: 'district', intensity: 'cataclysmic', rarity: 'grounded',
    minTier: 1, maxTier: 4,
    tags: ['storm','wind','debris','urban','rubble'],
    timePressure: ['funnel arriving in ninety seconds','debris field expanding'],
    movementConstraints: ['flying vehicles and signage','torn power lines whipping the street'],
    collateral: ['shoppers in glass-fronted stores','school dismissal in progress'],
    dynamicFactors: ['second twister forming','hail core preceding the funnel'],
  },
  {
    id: 'nat-tsunami-harbor',
    title: 'Tsunami Surge Into Working Harbor',
    concept: 'A subduction-zone wave drives container ships into a port district during shift change.',
    category: 'water-flooding', scope: 'city', intensity: 'cataclysmic', rarity: 'grounded',
    minTier: 1, maxTier: 4,
    tags: ['water','flood','urban','metal','rubble'],
    timePressure: ['wave arrival in three minutes','draw-down exposing harbor floor first'],
    movementConstraints: ['water-borne debris','collapsing piers','fuel slick on the surface'],
    collateral: ['dockworkers caught off-shift','cruise ship passengers boarding'],
    dynamicFactors: ['second and third waves','ignited fuel slick','container avalanche'],
  },
  {
    id: 'nat-hurricane-eyewall',
    title: 'Cat 5 Eyewall Over Coastal Resort',
    concept: 'The eyewall of a massive hurricane hits a high-rise resort during full occupancy.',
    category: 'atmospheric-storm', scope: 'city', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 4,
    tags: ['storm','wind','water','urban','debris'],
    timePressure: ['storm surge cresting','windows imploding floor by floor'],
    movementConstraints: ['horizontal rain reducing visibility','flooded ground floor','stairwell-only access'],
    collateral: ['evacuated guests in ballroom','staff trapped in service tunnels'],
    dynamicFactors: ['eye passing then back wall hitting','transformer explosion chain'],
  },
  {
    id: 'nat-blizzard-mountain-pass',
    title: 'Whiteout Blizzard on Mountain Pass',
    concept: 'A multi-vehicle pile-up on a mountain pass under whiteout conditions, hypothermia setting in.',
    category: 'cryogenic-arctic', scope: 'local', intensity: 'rising', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['ice','wind','rubble','wilderness'],
    timePressure: ['fuel running out in stranded cars','core temperatures dropping'],
    movementConstraints: ['knee-deep drifts','near-zero visibility','black ice underfoot'],
    collateral: ['family in wrecked SUV','tour bus passengers'],
    dynamicFactors: ['second avalanche above the road','fuel tanker overturning'],
  },
  {
    id: 'nat-avalanche-ski-resort',
    title: 'Class 5 Avalanche Onto Ski Resort',
    concept: 'A massive slab releases above a packed ski village mid-afternoon.',
    category: 'cryogenic-arctic', scope: 'district', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['ice','rubble','rock','wilderness'],
    timePressure: ['snow front fifteen seconds away','buried victims have minutes'],
    movementConstraints: ['compacted snow chest-deep','buried obstacles','treewells'],
    collateral: ['lift line skiers','ski school children','lodge diners'],
    dynamicFactors: ['secondary slide','propane line rupture under snow'],
  },
  {
    id: 'nat-sinkhole-suburb',
    title: 'Sinkhole Swallows Cul-de-Sac',
    concept: 'A limestone cavern collapses under a residential street, dragging houses into the void.',
    category: 'seismic-tectonic', scope: 'local', intensity: 'rising', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['rubble','rock','underground','urban'],
    timePressure: ['hole widening every minute','gas main about to shear'],
    movementConstraints: ['unstable rim','fragile foundations','tilted floors'],
    collateral: ['family in basement','mail carrier on route'],
    dynamicFactors: ['gas explosion','sewer flood from below','further collapse'],
  },
  {
    id: 'nat-mudslide-hillside-village',
    title: 'Mudslide Burying Hillside Village',
    concept: 'Saturated hillsides give way after a week of rain, sweeping homes into a river.',
    category: 'natural-disaster', scope: 'district', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['water','rubble','rock','wilderness'],
    timePressure: ['second slide imminent','river damming and about to burst'],
    movementConstraints: ['waist-deep mud','floating debris','collapsed footbridge'],
    collateral: ['villagers on rooftops','livestock in pens'],
    dynamicFactors: ['debris dam burst','sewage contamination'],
  },
  {
    id: 'nat-derecho-cornbelt',
    title: 'Derecho Sweeps Across Open Plains',
    concept: 'A 100mph straight-line wind event flattens grain silos and tosses rail cars.',
    category: 'atmospheric-storm', scope: 'regional', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 4,
    tags: ['storm','wind','metal','debris','rubble'],
    timePressure: ['winds escalating','hail core inbound'],
    movementConstraints: ['airborne sheet metal','collapsed grain elevators','live wires'],
    collateral: ['farmworkers in fields','small-town residents'],
    dynamicFactors: ['grain dust explosion','tornado spinup'],
  },
  {
    id: 'urb-skyscraper-progressive-collapse',
    title: 'Progressive Collapse of Office Tower',
    concept: 'A truck bomb in a parking garage triggers pancake collapse cascading floor by floor.',
    category: 'urban-collapse', scope: 'district', intensity: 'cataclysmic', rarity: 'grounded',
    minTier: 1, maxTier: 4,
    tags: ['rubble','smoke','urban','metal'],
    timePressure: ['floors pancaking every six seconds','remaining columns buckling'],
    movementConstraints: ['shifting rubble piles','severed elevator shafts','dust blackout'],
    collateral: ['office workers on upper floors','daycare on the third level'],
    dynamicFactors: ['secondary device','gas main rupture','adjacent tower lean'],
  },
  {
    id: 'urb-bridge-cable-failure',
    title: 'Suspension Bridge Cable Cascade',
    concept: 'Main suspension cables snap one by one over a busy strait at rush hour.',
    category: 'urban-collapse', scope: 'district', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['metal','rubble','water','urban'],
    timePressure: ['next cable snap in twenty seconds','deck twisting'],
    movementConstraints: ['tilted roadway','vehicles sliding','no shoulder'],
    collateral: ['bus full of commuters','cyclists in lane'],
    dynamicFactors: ['fuel truck igniting','tower base cracking'],
  },
  {
    id: 'urb-stadium-roof-collapse',
    title: 'Stadium Roof Collapse Mid-Concert',
    concept: 'A retractable stadium roof fails during a sold-out concert, panels falling onto the crowd.',
    category: 'urban-collapse', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['metal','rubble','urban','crowd'],
    timePressure: ['support trusses failing in series','panic crush at exits'],
    movementConstraints: ['dense crowd','seating debris','dim emergency lighting'],
    collateral: ['eighty thousand attendees','performers on stage'],
    dynamicFactors: ['stage rigging falling','pyrotechnics igniting fallen drapes'],
  },
  {
    id: 'urb-parking-garage-pancake',
    title: 'Multi-Story Parking Garage Pancake',
    concept: 'Corroded post-tension cables let a parking structure flatten at quitting time.',
    category: 'urban-collapse', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['rubble','metal','urban','smoke'],
    timePressure: ['next deck failing','fire from ruptured tanks'],
    movementConstraints: ['crushed vehicles','low headroom','rebar everywhere'],
    collateral: ['drivers in their cars','attendant in booth'],
    dynamicFactors: ['fuel pool fire','adjacent building damage'],
  },
  {
    id: 'urb-construction-crane-fall',
    title: 'Tower Crane Toppling Over Downtown',
    concept: 'A construction tower crane snaps at the slewing ring and topples across a city block.',
    category: 'urban-collapse', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['metal','rubble','urban','debris'],
    timePressure: ['crane swinging through arc','counterweight detaching'],
    movementConstraints: ['fall path through buildings','glass rain'],
    collateral: ['lunch crowd on sidewalk','construction crew on site'],
    dynamicFactors: ['load drop','adjacent crane domino'],
  },
  {
    id: 'urb-historic-facade-collapse',
    title: 'Historic Building Facade Sheers Off',
    concept: 'An old masonry facade peels away from a renovated landmark onto a packed plaza.',
    category: 'urban-collapse', scope: 'local', intensity: 'rising', rarity: 'grounded',
    minTier: 1, maxTier: 2,
    tags: ['rubble','rock','urban'],
    timePressure: ['mortar crumbling visibly','remaining ties failing'],
    movementConstraints: ['falling masonry blocks','dust cloud'],
    collateral: ['street performers','cafe patrons','tourists'],
    dynamicFactors: ['interior floor collapse','rear wall failure'],
  },
  {
    id: 'urb-sewer-cavein',
    title: 'Sewer Tunnel Cave-In Below Intersection',
    concept: 'An aging brick sewer collapses, dropping a busy intersection into raw sewage.',
    category: 'urban-collapse', scope: 'local', intensity: 'rising', rarity: 'grounded',
    minTier: 1, maxTier: 2,
    tags: ['underground','toxic','water','urban','rubble'],
    timePressure: ['hole widening','methane reaching ignition'],
    movementConstraints: ['contaminated water','dark tunnels','rebar tangles'],
    collateral: ['drivers in submerged cars','utility crew below'],
    dynamicFactors: ['methane explosion','water main rupture'],
  },
  {
    id: 'tra-train-derailment-bridge',
    title: 'Freight Derailment on Trestle Bridge',
    concept: 'A high-speed freight derails on an elevated trestle, tank cars dangling and leaking.',
    category: 'transport-crisis', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['metal','rubble','toxic','smoke','infrastructure'],
    timePressure: ['leaking chlorine cloud drifting','trestle creaking under shifted load'],
    movementConstraints: ['narrow trestle walkway','dangling cars','toxic plume'],
    collateral: ['town downwind','engineer in cab'],
    dynamicFactors: ['ignition of fuel cars','full bridge collapse'],
  },
  {
    id: 'tra-airliner-emergency-landing',
    title: 'Airliner Belly-Landing on Highway',
    concept: 'A wide-body jet loses both engines and lines up on a packed interstate.',
    category: 'transport-crisis', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 4,
    tags: ['metal','fire','smoke','urban','infrastructure'],
    timePressure: ['glide slope steepening','fuel pooling on touchdown'],
    movementConstraints: ['highway traffic','overpasses in glide path','wing clearance'],
    collateral: ['three hundred passengers','rush-hour drivers'],
    dynamicFactors: ['post-impact fire','overpass strike'],
  },
  {
    id: 'tra-cruise-ship-listing',
    title: 'Cruise Ship Listing in Open Sea',
    concept: 'A pod failure and engine room flood put a mega-cruiser at thirty degrees of list.',
    category: 'maritime-deepwater', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['water','metal','infrastructure'],
    timePressure: ['list increasing one degree per minute','lifeboats now unlaunchable on high side'],
    movementConstraints: ['sloped decks','flooded corridors','jammed bulkhead doors'],
    collateral: ['four thousand passengers','crew below decks'],
    dynamicFactors: ['power failure','full capsize'],
  },
  {
    id: 'tra-subway-rear-end',
    title: 'Subway Rear-End Inside Tunnel',
    concept: 'Two trains collide deep inside a river tunnel, smoke filling the bore.',
    category: 'transport-crisis', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 2,
    tags: ['underground','smoke','metal','rubble','urban'],
    timePressure: ['oxygen depleting','tunnel structurally compromised'],
    movementConstraints: ['third rail still hot','crushed carriages','smoke blackout'],
    collateral: ['rush-hour passengers','train operators'],
    dynamicFactors: ['tunnel flooding from breach','battery fire'],
  },
  {
    id: 'tra-tanker-truck-tunnel-fire',
    title: 'Fuel Tanker Inferno Inside Highway Tunnel',
    concept: 'A fuel tanker overturns and ignites inside a long tunnel during peak traffic.',
    category: 'fire-conflagration', scope: 'local', intensity: 'cataclysmic', rarity: 'grounded',
    minTier: 1, maxTier: 4,
    tags: ['fire','smoke','underground','metal','urban'],
    timePressure: ['temperature rising past steel softening','ventilation failing'],
    movementConstraints: ['vehicles abandoned','superheated air','dense smoke'],
    collateral: ['hundreds trapped','tunnel crew'],
    dynamicFactors: ['concrete spalling','second tanker BLEVE'],
  },
  {
    id: 'tra-helicopter-crash-rooftop',
    title: 'Medevac Helicopter Crash on Hospital Roof',
    concept: 'A medical helicopter loses tail rotor authority and crashes onto a hospital helipad.',
    category: 'transport-crisis', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['fire','metal','rubble','urban'],
    timePressure: ['fuel pooling toward HVAC intake','rotor blades still spinning'],
    movementConstraints: ['rooftop edges','fire suppression mist','wreckage'],
    collateral: ['patient onboard','ICU one floor below'],
    dynamicFactors: ['hospital evacuation cascade','helipad collapse'],
  },
  {
    id: 'tra-runway-incursion',
    title: 'Runway Incursion at International Airport',
    concept: 'A taxiing widebody and a landing jet are seconds from collision on the main runway.',
    category: 'transport-crisis', scope: 'local', intensity: 'cataclysmic', rarity: 'grounded',
    minTier: 1, maxTier: 4,
    tags: ['fire','metal','smoke','infrastructure'],
    timePressure: ['ten seconds to impact','no go-around possible'],
    movementConstraints: ['open runway','no cover','jet wash'],
    collateral: ['both aircraft full','ground crew'],
    dynamicFactors: ['fuel fireball','terminal evacuation'],
  },
  {
    id: 'tra-cargo-ship-bridge-strike',
    title: 'Container Ship Drifts Into Bridge Pier',
    concept: 'A black-out container vessel drifts toward a major highway bridge pier.',
    category: 'transport-crisis', scope: 'district', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['water','metal','rubble','urban'],
    timePressure: ['three minutes to impact','tide accelerating drift'],
    movementConstraints: ['water gap','no tug response','live traffic on bridge'],
    collateral: ['bridge commuters','ship crew of twenty'],
    dynamicFactors: ['span collapse','fuel spill ignition'],
  },
  {
    id: 'ind-reactor-coolant-loss',
    title: 'Reactor Coolant System Loss',
    concept: 'A pressurized water reactor loses primary coolant; core temperature climbing fast.',
    category: 'energy-overload', scope: 'regional', intensity: 'cataclysmic', rarity: 'grounded',
    minTier: 2, maxTier: 4,
    tags: ['radiation','fire','infrastructure','energy','metal'],
    timePressure: ['core uncovered in minutes','containment pressure rising'],
    movementConstraints: ['radiation hot spots','steam jets','locked-down corridors'],
    collateral: ['plant staff','downwind population'],
    dynamicFactors: ['hydrogen explosion','full containment breach'],
  },
  {
    id: 'ind-refinery-cracking-tower',
    title: 'Refinery Cracking Tower Overpressure',
    concept: 'A petrochemical cracking tower goes overpressure; relief valves stuck closed.',
    category: 'industrial-meltdown', scope: 'district', intensity: 'critical', rarity: 'grounded',
    minTier: 2, maxTier: 4,
    tags: ['fire','toxic','metal','infrastructure','smoke'],
    timePressure: ['tower about to rupture','flare stack failing'],
    movementConstraints: ['hot piping','flammable vapor cloud','catwalks only'],
    collateral: ['shift crew','tank-farm neighbors'],
    dynamicFactors: ['vapor cloud explosion','BLEVE chain'],
  },
  {
    id: 'ind-grain-silo-dust-explosion',
    title: 'Grain Silo Dust Explosion Cascade',
    concept: 'A dust-rich grain silo ignites; chain explosions ripple down the elevator row.',
    category: 'industrial-meltdown', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['fire','smoke','metal','infrastructure'],
    timePressure: ['next silo igniting in seconds','workers buried in collapsed bin'],
    movementConstraints: ['burning grain piles','collapsed catwalks','silo confined spaces'],
    collateral: ['millworkers','rail crew loading cars'],
    dynamicFactors: ['secondary detonations','elevator collapse'],
  },
  {
    id: 'ind-foundry-ladle-spill',
    title: 'Steel Foundry Ladle Spills Molten Steel',
    concept: 'An overhead crane fails and dumps a ladle of molten steel across the foundry floor.',
    category: 'industrial-meltdown', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 2, maxTier: 4,
    tags: ['fire','metal','smoke','infrastructure'],
    timePressure: ['steel pooling toward water lines','crane swinging again'],
    movementConstraints: ['molten pools','radiant heat','steam from contact with water'],
    collateral: ['foundry crew','pour observers'],
    dynamicFactors: ['steam explosion','crane runway collapse'],
  },
  {
    id: 'ind-chemical-storage-cascade',
    title: 'Chemical Storage Tank Farm Cascade',
    concept: 'A leaking specialty chemicals tank threatens to mix incompatibles across a tank farm.',
    category: 'chemical-radiological', scope: 'district', intensity: 'critical', rarity: 'grounded',
    minTier: 2, maxTier: 4,
    tags: ['toxic','fire','metal','smoke'],
    timePressure: ['incompatible reaction in three minutes','wind shifting toward town'],
    movementConstraints: ['SCBA required','spill puddles','vapor pockets'],
    collateral: ['plant operators','community evacuating'],
    dynamicFactors: ['exothermic runaway','tank rocket'],
  },
  {
    id: 'ind-mine-explosion-collapse',
    title: 'Methane Explosion Deep in Coal Mine',
    concept: 'A methane pocket ignites a kilometer underground, collapsing the main drift.',
    category: 'subterranean-cavern', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['underground','smoke','rubble','rock'],
    timePressure: ['oxygen dropping','second pocket about to ignite'],
    movementConstraints: ['blocked drift','low ceilings','headlamp-only light'],
    collateral: ['fifty miners on shift','rescue team entering'],
    dynamicFactors: ['fire damp explosion','flooding from severed water line'],
  },
  {
    id: 'ind-power-plant-turbine-burst',
    title: 'Steam Turbine Burst at Power Plant',
    concept: 'A 600MW turbine blade lets go, shrapnel shredding the turbine hall.',
    category: 'mechanical-runaway', scope: 'local', intensity: 'cataclysmic', rarity: 'grounded',
    minTier: 2, maxTier: 4,
    tags: ['metal','fire','smoke','energy','infrastructure'],
    timePressure: ['steam still venting','adjacent unit accelerating without load'],
    movementConstraints: ['shrapnel field','superheated steam jets','oil fires'],
    collateral: ['control-room operators','maintenance crew'],
    dynamicFactors: ['hydrogen-cooled generator fire','grid cascade'],
  },
  {
    id: 'ind-paper-mill-recovery-boiler',
    title: 'Recovery Boiler Smelt-Water Explosion',
    concept: 'A pulp-mill recovery boiler suffers a smelt-water explosion, blowing out the back wall.',
    category: 'industrial-meltdown', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 2, maxTier: 3,
    tags: ['fire','smoke','metal','toxic'],
    timePressure: ['black liquor still feeding','second explosion possible'],
    movementConstraints: ['steam fog','rubble piles','toxic gas pockets'],
    collateral: ['mill workers','adjacent paper machine crew'],
    dynamicFactors: ['fire spreading to wood yard','sulfur cloud release'],
  },
  {
    id: 'inf-dam-piping-failure',
    title: 'Dam Suffering Internal Erosion',
    concept: 'Sand boils at the base of an earthen dam signal imminent piping failure.',
    category: 'infrastructure-failure', scope: 'regional', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 4,
    tags: ['water','flood','rubble','infrastructure'],
    timePressure: ['breach in twenty minutes','town below unwarned'],
    movementConstraints: ['saturated slopes','rising tailwater','spillway turbulence'],
    collateral: ['valley population of forty thousand','downstream bridges'],
    dynamicFactors: ['full breach','cascading failures of downstream weirs'],
  },
  {
    id: 'inf-power-grid-cascade',
    title: 'Citywide Power Grid Cascade Failure',
    concept: 'A heatwave overloads transformers; substations explode in sequence across the metro.',
    category: 'infrastructure-failure', scope: 'city', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['energy','fire','urban','infrastructure'],
    timePressure: ['next substation failing','hospitals on backup running out'],
    movementConstraints: ['blacked-out streets','stuck elevators','dark intersections'],
    collateral: ['ICU patients on ventilators','people in subways','elderly without AC'],
    dynamicFactors: ['transformer fires igniting brush','riot triggers'],
  },
  {
    id: 'inf-water-main-burst',
    title: 'Trunk Water Main Burst Floods District',
    concept: 'A 60-inch trunk main bursts under a busy district, undermining streets.',
    category: 'infrastructure-failure', scope: 'district', intensity: 'rising', rarity: 'grounded',
    minTier: 1, maxTier: 2,
    tags: ['water','flood','urban','infrastructure'],
    timePressure: ['streets undercutting','sinkholes opening'],
    movementConstraints: ['waist-deep water','floating debris','collapsed pavement'],
    collateral: ['ground-floor businesses','basement apartments'],
    dynamicFactors: ['gas main shear','traffic light short circuits'],
  },
  {
    id: 'inf-natural-gas-main-rupture',
    title: 'Distribution Gas Main Rupture in Neighborhood',
    concept: 'A construction strike ruptures a high-pressure gas main; vapor cloud spreading.',
    category: 'infrastructure-failure', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['fire','toxic','urban','infrastructure'],
    timePressure: ['ignition source feared','vapor reaching homes'],
    movementConstraints: ['no sparks allowed','evacuate-only zones','low spots filling'],
    collateral: ['homes in vapor zone','school down the block'],
    dynamicFactors: ['vapor cloud explosion','house-by-house ignition'],
  },
  {
    id: 'inf-aqueduct-collapse',
    title: 'Roman-Era Aqueduct Section Collapse',
    concept: 'A stone aqueduct over a market square gives way during a festival.',
    category: 'infrastructure-failure', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['water','rubble','rock','urban','crowd'],
    timePressure: ['next arch failing','crowd panic crush'],
    movementConstraints: ['fallen masonry','wet flagstones','dense crowd'],
    collateral: ['festival-goers','vendor stalls'],
    dynamicFactors: ['flash flood from severed channel','full row collapse'],
  },
  {
    id: 'inf-data-center-fire',
    title: 'Hyperscale Data Center Battery Fire',
    concept: 'A lithium battery room thermal-runs in a data center hosting hospitals and grid control.',
    category: 'fire-conflagration', scope: 'regional', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['fire','toxic','smoke','energy','infrastructure'],
    timePressure: ['suppression overwhelmed','adjacent battery rooms heating'],
    movementConstraints: ['toxic HF smoke','locked server cages','raised floors'],
    collateral: ['operators inside','hospitals losing telemetry'],
    dynamicFactors: ['cascading battery fires','full grid loss'],
  },
  {
    id: 'inf-wind-farm-blade-failure',
    title: 'Offshore Wind Turbine Blade Throw',
    concept: 'A massive offshore turbine sheds a blade in a storm; tower listing.',
    category: 'infrastructure-failure', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 2, maxTier: 4,
    tags: ['water','metal','wind','infrastructure'],
    timePressure: ['tower swaying past tolerance','second blade failing'],
    movementConstraints: ['rough seas','swinging blade','platform tilt'],
    collateral: ['service crew on platform','passing fishing boat'],
    dynamicFactors: ['full tower collapse','transformer oil fire'],
  },
  {
    id: 'inf-pipeline-jet-fire',
    title: 'Natural Gas Pipeline Jet Fire',
    concept: 'A high-pressure gas pipeline ruptures and ignites in a residential greenbelt.',
    category: 'infrastructure-failure', scope: 'district', intensity: 'cataclysmic', rarity: 'grounded',
    minTier: 1, maxTier: 4,
    tags: ['fire','smoke','infrastructure','urban'],
    timePressure: ['radiant heat igniting houses','isolation valves slow to close'],
    movementConstraints: ['hundred-meter heat exclusion','melting asphalt','smoke column'],
    collateral: ['evacuating subdivision','responders in heat zone'],
    dynamicFactors: ['secondary line involvement','wildland fire spread'],
  },
  {
    id: 'chm-rail-chlorine-release',
    title: 'Chlorine Tank Car Release',
    concept: 'A derailed tank car vents chlorine; a green-yellow plume rolls into a town.',
    category: 'chemical-radiological', scope: 'district', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['toxic','smoke','urban','wind'],
    timePressure: ['plume crossing town in minutes','wind shifting'],
    movementConstraints: ['low-lying gas pockets','no breathable air','blinded responders'],
    collateral: ['school nearby','hospital downwind'],
    dynamicFactors: ['second car releasing','rain creating acid runoff'],
  },
  {
    id: 'chm-orphan-radiological-source',
    title: 'Orphan Radiological Source in Scrap Yard',
    concept: 'An unshielded medical source ends up in a scrapyard shredder, contaminating a district.',
    category: 'chemical-radiological', scope: 'district', intensity: 'rising', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['radiation','metal','smoke','infrastructure'],
    timePressure: ['exposure climbing per second near source','source about to be loaded onto truck'],
    movementConstraints: ['hot zone unmarked','metal piles blocking line of sight'],
    collateral: ['scrap workers','nearby workshop'],
    dynamicFactors: ['source breached during shred','contaminated dust spreading'],
  },
  {
    id: 'chm-clandestine-lab-fire',
    title: 'Clandestine Drug Lab Fire',
    concept: 'A meth or fentanyl lab catches fire in a residential apartment block.',
    category: 'chemical-radiological', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['fire','toxic','smoke','urban'],
    timePressure: ['fire breaching ceiling','chemicals reacting'],
    movementConstraints: ['narrow apartment hallways','toxic smoke','solvent puddles'],
    collateral: ['neighbors trapped','infants in adjacent unit'],
    dynamicFactors: ['solvent flash fire','full block evacuation'],
  },
  {
    id: 'chm-pesticide-warehouse-fire',
    title: 'Pesticide Warehouse Inferno',
    concept: 'An agricultural pesticide warehouse burns; runoff and smoke threaten a watershed.',
    category: 'chemical-radiological', scope: 'regional', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['fire','toxic','smoke','water'],
    timePressure: ['runoff reaching river','drum cookoff imminent'],
    movementConstraints: ['SCBA only','collapsing roof trusses','chemical foam everywhere'],
    collateral: ['farming community','town water intake'],
    dynamicFactors: ['BLEVE of solvent drums','contaminated runoff plume'],
  },
  {
    id: 'bio-quarantine-breach-hospital',
    title: 'Biosafety Quarantine Breach in Hospital',
    concept: 'A high-containment patient escapes the negative-pressure ward during a power flicker.',
    category: 'biological-outbreak', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['toxic','urban','infrastructure'],
    timePressure: ['contagion timer ticking','HVAC needs shutdown manually'],
    movementConstraints: ['PPE bottlenecks','locked-down wings','crowded ER'],
    collateral: ['ICU patients','visiting families'],
    dynamicFactors: ['secondary cases appearing','riot at quarantine line'],
  },
  {
    id: 'bio-livestock-pathogen-stampede',
    title: 'Pathogen-Driven Livestock Stampede',
    concept: 'A neurotoxin-tainted feed lot turns thousands of cattle into a panicked stampede.',
    category: 'biological-outbreak', scope: 'district', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['wilderness','rubble','crowd'],
    timePressure: ['herd reaching highway','contagion spreading to handlers'],
    movementConstraints: ['hooves and dust','collapsing pen fences','no vehicle traction'],
    collateral: ['ranch hands','rural school bus route'],
    dynamicFactors: ['vehicle pile-up','panic at adjacent feedlots'],
  },
  {
    id: 'bio-mosquito-vector-bloom',
    title: 'Disease Vector Mosquito Bloom in Refugee Camp',
    concept: 'Stagnant flooding spawns a vector mosquito bloom inside a crowded camp.',
    category: 'biological-outbreak', scope: 'district', intensity: 'rising', rarity: 'grounded',
    minTier: 1, maxTier: 2,
    tags: ['toxic','water','crowd'],
    timePressure: ['nightfall accelerating bites','clinic overrun by morning'],
    movementConstraints: ['mud lanes','crowded tents','no nets'],
    collateral: ['displaced families','overworked medics'],
    dynamicFactors: ['cholera outbreak overlay','flood pulse'],
  },
  {
    id: 'crd-stadium-crush',
    title: 'Crowd Crush at Stadium Gate',
    concept: 'A bottlenecked stadium gate becomes a crowd crush as more push from behind.',
    category: 'crowd-panic', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 2,
    tags: ['crowd','urban'],
    timePressure: ['front row losing consciousness','more arriving every second'],
    movementConstraints: ['no air','no movement','people upright but immobile'],
    collateral: ['thousands packed','children at front'],
    dynamicFactors: ['fence collapse','fight breaking out'],
  },
  {
    id: 'crd-festival-stage-collapse',
    title: 'Festival Stage Rigging Collapse',
    concept: 'Wind gusts collapse a festival stage onto the front of the crowd.',
    category: 'crowd-panic', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['rubble','metal','crowd'],
    timePressure: ['second tower falling','speakers crashing down'],
    movementConstraints: ['fallen rigging','panicked crowd','muddy field'],
    collateral: ['front-row fans','performers','crew'],
    dynamicFactors: ['LED wall topple','lighting truss chain reaction'],
  },
  {
    id: 'crd-religious-pilgrimage-bridge',
    title: 'Pilgrimage Bridge Crush',
    concept: 'A pedestrian bridge during a major pilgrimage hits critical density.',
    category: 'crowd-panic', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 2,
    tags: ['crowd','urban','metal'],
    timePressure: ['handrails giving way','panic wave starting'],
    movementConstraints: ['no return','no exit','people falling'],
    collateral: ['tens of thousands of pilgrims'],
    dynamicFactors: ['railing failure dropping people','bridge structural shake'],
  },
  {
    id: 'crd-school-evacuation-panic',
    title: 'School Evacuation Panic',
    concept: 'A false alarm becomes deadly as a school evacuation panics down narrow stairwells.',
    category: 'crowd-panic', scope: 'local', intensity: 'rising', rarity: 'grounded',
    minTier: 1, maxTier: 2,
    tags: ['crowd','urban'],
    timePressure: ['younger kids being trampled','exits jammed'],
    movementConstraints: ['narrow stairwells','locked side doors','panicked adults'],
    collateral: ['hundreds of children','teachers'],
    dynamicFactors: ['actual fire developing','parent surge at gate'],
  },
  {
    id: 'sub-cave-rescue-flooding',
    title: 'Cave Diver Trapped by Flood Pulse',
    concept: 'A cave system fills after a sudden surface storm; explorers stranded in air pockets.',
    category: 'subterranean-cavern', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['water','flood','underground','rock','wilderness'],
    timePressure: ['air pocket shrinking','water clarity gone'],
    movementConstraints: ['narrow squeezes','zero visibility','strong currents'],
    collateral: ['stranded children','rescue diver in trouble'],
    dynamicFactors: ['second flood pulse','rockfall blocking exit'],
  },
  {
    id: 'sub-deep-tunnel-blowout',
    title: 'TBM Pressurized Face Blowout',
    concept: 'A tunnel boring machine experiences a face blowout under a river.',
    category: 'subterranean-cavern', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 2, maxTier: 4,
    tags: ['water','flood','underground','rubble','metal'],
    timePressure: ['water inrush filling tunnel','crew sealed behind bulkhead'],
    movementConstraints: ['narrow tunnel','jammed personnel locks','dark water'],
    collateral: ['tunnel crew of thirty'],
    dynamicFactors: ['full segment collapse','river bed slumping above'],
  },
  {
    id: 'sub-lava-tube-collapse',
    title: 'Lava Tube Roof Collapse Onto Tour Group',
    concept: 'A volcanic lava tube ceiling caves in onto a tourist group on an island.',
    category: 'subterranean-cavern', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['rock','rubble','underground','wilderness'],
    timePressure: ['next section creaking','injured trapped under slabs'],
    movementConstraints: ['jagged basalt','headlamp-only','no ventilation'],
    collateral: ['tour group','guide'],
    dynamicFactors: ['secondary collapse','vog gas pocket release'],
  },
  {
    id: 'mar-submarine-sinking',
    title: 'Research Submarine Stuck on Trench Wall',
    concept: 'A research submersible is wedged against a trench wall; oxygen running out.',
    category: 'maritime-deepwater', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 2, maxTier: 4,
    tags: ['water','metal','underground'],
    timePressure: ['oxygen hours dwindling','hull groaning under pressure'],
    movementConstraints: ['cramped sub interior','external pitch dark'],
    collateral: ['three crew aboard','support ship racing'],
    dynamicFactors: ['hull breach','pinger battery dying'],
  },
  {
    id: 'mar-rogue-wave-fishing-fleet',
    title: 'Rogue Wave Hits Fishing Fleet',
    concept: 'A rogue wave swamps a small fishing fleet at the harbor entrance.',
    category: 'maritime-deepwater', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['water','wind','metal','wilderness'],
    timePressure: ['second wave incoming','crews in cold water'],
    movementConstraints: ['heavy seas','capsized hulls','tangled nets'],
    collateral: ['dozens of crew','harbormaster boat'],
    dynamicFactors: ['fuel slick fire','breakwater collapse'],
  },
  {
    id: 'mar-oil-platform-blowout',
    title: 'Offshore Platform Wellhead Blowout',
    concept: 'A drilling platform suffers a wellhead blowout; gas plume and fire on the deck.',
    category: 'maritime-deepwater', scope: 'district', intensity: 'cataclysmic', rarity: 'grounded',
    minTier: 2, maxTier: 4,
    tags: ['fire','water','metal','toxic','smoke','infrastructure'],
    timePressure: ['platform tilting','helideck unusable'],
    movementConstraints: ['hot decks','jammed lifeboat davits','smoke','sea swell'],
    collateral: ['hundred-person crew'],
    dynamicFactors: ['platform leg failure','riser collapse'],
  },
  {
    id: 'mar-iceberg-strike-cruiseship',
    title: 'Iceberg Strike on Polar Cruise',
    concept: 'A polar expedition cruise strikes an unmapped berg; hull breached at the bow.',
    category: 'maritime-deepwater', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['water','ice','metal','wilderness'],
    timePressure: ['bow flooding fast','help six hours away'],
    movementConstraints: ['sloped decks','frozen davits','sub-zero air'],
    collateral: ['guests on excursion','crew'],
    dynamicFactors: ['second berg drift-in','engine room flood'],
  },
  {
    id: 'atm-microburst-airshow',
    title: 'Microburst Slams Airshow',
    concept: 'A microburst hits an airshow as aerobatic teams pass low over the crowd.',
    category: 'atmospheric-storm', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['wind','fire','crowd','rubble','metal'],
    timePressure: ['aircraft dropping out of sky','tents lifting'],
    movementConstraints: ['flying debris','panicked crowd','aircraft fragments'],
    collateral: ['airshow crowd','pilots','show staff'],
    dynamicFactors: ['secondary downburst','fuel fire'],
  },
  {
    id: 'atm-haboob-desert-highway',
    title: 'Haboob Dust Storm Engulfs Highway',
    concept: 'A wall of dust hits a desert interstate, blinding drivers in seconds.',
    category: 'atmospheric-storm', scope: 'regional', intensity: 'rising', rarity: 'grounded',
    minTier: 1, maxTier: 2,
    tags: ['wind','fog','urban','metal'],
    timePressure: ['pile-ups starting','breathing impaired'],
    movementConstraints: ['zero visibility','dust-clogged engines','stopped vehicles'],
    collateral: ['highway travelers','elderly with respiratory issues'],
    dynamicFactors: ['fuel tanker pile-up fire','derecho overlay'],
  },
  {
    id: 'atm-ice-storm-grid-down',
    title: 'Crippling Ice Storm with Grid Failure',
    concept: 'A multi-day ice storm collapses transmission lines, power out across a state.',
    category: 'atmospheric-storm', scope: 'regional', intensity: 'rising', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['ice','wind','infrastructure','energy','wilderness'],
    timePressure: ['hypothermia cases mounting','tree limbs failing onto cars'],
    movementConstraints: ['glazed roads','falling limbs','dark intersections'],
    collateral: ['rural elderly','hospitals on gens'],
    dynamicFactors: ['transformer fires','generator carbon monoxide deaths'],
  },
  {
    id: 'sei-megaquake-megacity',
    title: 'Megaquake Hits Mega-City',
    concept: 'An M8.5 thrust quake levels older neighborhoods of a coastal megacity.',
    category: 'seismic-tectonic', scope: 'city', intensity: 'cataclysmic', rarity: 'grounded',
    minTier: 1, maxTier: 4,
    tags: ['rubble','rock','urban','smoke','fire'],
    timePressure: ['aftershocks every few minutes','tsunami inbound'],
    movementConstraints: ['rubble-blocked streets','collapsed overpasses','dust','severed water'],
    collateral: ['millions','hospitals already overwhelmed'],
    dynamicFactors: ['major aftershock','tsunami arrival','firestorm'],
  },
  {
    id: 'sei-liquefaction-port',
    title: 'Soil Liquefaction Sinks Port District',
    concept: 'An earthquake liquefies fill under a port district; cranes tipping, ships listing.',
    category: 'seismic-tectonic', scope: 'district', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['rubble','water','urban','metal'],
    timePressure: ['cranes falling','quayside dropping into bay'],
    movementConstraints: ['mud-like ground','tilted containers','spreading cracks'],
    collateral: ['dock crews','crew of berthed ships'],
    dynamicFactors: ['fuel slick fire','tsunami amplification'],
  },
  {
    id: 'sei-volcano-pyroclastic',
    title: 'Pyroclastic Flow Down Volcano Flank',
    concept: 'A stratovolcano sends a pyroclastic flow toward a tourist village.',
    category: 'volcanic-thermal', scope: 'district', intensity: 'cataclysmic', rarity: 'grounded',
    minTier: 1, maxTier: 4,
    tags: ['fire','smoke','rock','wilderness'],
    timePressure: ['flow front in nine minutes','ashfall blacking out sky'],
    movementConstraints: ['hot ash','blocked roads','no air','heat blast'],
    collateral: ['village','climbers on lower slopes','tour buses'],
    dynamicFactors: ['second flow','lahar from melted snow'],
  },
  {
    id: 'sei-lahar-mountain-town',
    title: 'Lahar Sweeps Through Mountain Town',
    concept: 'A volcanic mudflow surges down a river valley toward a sleeping town.',
    category: 'volcanic-thermal', scope: 'district', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['water','rubble','rock','wilderness','urban'],
    timePressure: ['lahar arriving in twenty minutes','town slow to wake'],
    movementConstraints: ['concrete-thick mud','floating houses','swept bridges'],
    collateral: ['several thousand residents','overnight tourists'],
    dynamicFactors: ['secondary surge','cold lahar after main pulse'],
  },
  {
    id: 'sei-volcano-ashfall-airport',
    title: 'Ashfall Closing Major Airport',
    concept: 'Volcanic ash blankets a hub airport mid-operation; aircraft engines flame out.',
    category: 'volcanic-thermal', scope: 'regional', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['toxic','smoke','metal','infrastructure','urban'],
    timePressure: ['aircraft inbound on fumes','roof loads building'],
    movementConstraints: ['slick ash on taxiways','poor visibility','HVAC clogged'],
    collateral: ['stranded passengers','flight crews'],
    dynamicFactors: ['terminal roof partial collapse','cargo fire'],
  },
  {
    id: 'cry-research-station-fire',
    title: 'Antarctic Research Station Fire',
    concept: 'A galley fire at a polar research station in winter night, no rescue for months.',
    category: 'cryogenic-arctic', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['fire','ice','wind','wilderness','infrastructure'],
    timePressure: ['fire reaching fuel storage','exposure killing those outside'],
    movementConstraints: ['80mph katabatic wind','-60C exposure','smoke in narrow corridors'],
    collateral: ['twenty-person winter crew'],
    dynamicFactors: ['fuel bladder rupture','generator loss'],
  },
  {
    id: 'cry-icebreaker-stuck',
    title: 'Icebreaker Trapped in Closing Ice',
    concept: 'An icebreaker is caught between converging floes during a polar storm.',
    category: 'cryogenic-arctic', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 2, maxTier: 4,
    tags: ['ice','water','metal','wind'],
    timePressure: ['hull pressure rising','storm intensifying'],
    movementConstraints: ['pack ice','frozen rigging','blizzard'],
    collateral: ['ship crew','science party'],
    dynamicFactors: ['hull breach','crush failure'],
  },
  {
    id: 'mil-uxo-construction-find',
    title: 'WWII UXO Found Under Construction Site',
    concept: 'A construction crew unearths a 500kg unexploded WWII bomb in a city center.',
    category: 'military-ordnance', scope: 'district', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['fire','rubble','urban','infrastructure'],
    timePressure: ['fuse degraded','evacuation incomplete'],
    movementConstraints: ['exclusion zone','rebar pit','sandbag shielding'],
    collateral: ['surrounding blocks of residents','hospital nearby'],
    dynamicFactors: ['secondary device','disposal team mistake'],
  },
  {
    id: 'mil-ammo-depot-fire',
    title: 'Ammunition Depot Fire',
    concept: 'A wildfire reaches a military ammunition depot; cookoffs starting in bunkers.',
    category: 'military-ordnance', scope: 'regional', intensity: 'cataclysmic', rarity: 'grounded',
    minTier: 1, maxTier: 4,
    tags: ['fire','smoke','wilderness','metal','infrastructure'],
    timePressure: ['next bunker about to cook off','wildfire wall closing'],
    movementConstraints: ['shrapnel exclusion zones','flaming brush','blast craters'],
    collateral: ['base personnel','firefighting aircraft','nearby town'],
    dynamicFactors: ['mass detonation','warhead chain'],
  },
  {
    id: 'mil-naval-vessel-magazine-fire',
    title: 'Magazine Fire Aboard Naval Vessel',
    concept: 'A fire reaches the magazine of a docked warship; suppression failing.',
    category: 'military-ordnance', scope: 'local', intensity: 'cataclysmic', rarity: 'grounded',
    minTier: 2, maxTier: 4,
    tags: ['fire','metal','smoke','infrastructure','water'],
    timePressure: ['cookoff imminent','flooding system jammed'],
    movementConstraints: ['cramped passageways','smoke','closed water-tight doors'],
    collateral: ['ship complement','dock workers'],
    dynamicFactors: ['secondary explosion','adjacent ship fire'],
  },
  {
    id: 'orb-station-decompression',
    title: 'Module Decompression on Orbital Station',
    concept: 'A micrometeoroid punctures a station module; air rushing into vacuum.',
    category: 'orbital-aerospace', scope: 'local', intensity: 'critical', rarity: 'advanced',
    minTier: 2, maxTier: 5,
    tags: ['space','metal','energy','infrastructure'],
    timePressure: ['module pressure dropping','hatches auto-sealing'],
    movementConstraints: ['microgravity','tools floating away','hatches closing on you'],
    collateral: ['off-shift astronauts','EVA crew outside'],
    dynamicFactors: ['cascade leak','cooling loop loss'],
  },
  {
    id: 'orb-debris-field-cascade',
    title: 'Kessler Cascade Through Orbital Lane',
    concept: 'A satellite collision spawns a debris cascade through a busy orbital lane.',
    category: 'orbital-aerospace', scope: 'planetary', intensity: 'critical', rarity: 'advanced',
    minTier: 3, maxTier: 5,
    tags: ['space','debris','metal','energy'],
    timePressure: ['next collision in seconds','orbital window closing'],
    movementConstraints: ['micro-debris swarms','no atmosphere','vector planning required'],
    collateral: ['inhabited stations','GPS constellation'],
    dynamicFactors: ['second cascade tier','planetary surface debris fall'],
  },
  {
    id: 'orb-warp-drive-overload',
    title: 'Warp Drive Containment Overload',
    concept: 'A starship’s warp coil containment is failing; minutes to safe ejection.',
    category: 'sci-fi-advanced', scope: 'local', intensity: 'cataclysmic', rarity: 'advanced',
    minTier: 3, maxTier: 5,
    tags: ['energy','space','metal','infrastructure'],
    timePressure: ['containment failure ETA','crew evacuating decks'],
    movementConstraints: ['radiation corridors','jammed blast doors','low-G after gravplate failure'],
    collateral: ['crew','passengers','docked tender'],
    dynamicFactors: ['secondary coil failure','antimatter feed rupture'],
  },
  {
    id: 'orb-solar-flare-station',
    title: 'X-Class Solar Flare Strikes Outpost',
    concept: 'A massive solar flare batters a thin-shielded outpost between worlds.',
    category: 'orbital-aerospace', scope: 'planetary', intensity: 'critical', rarity: 'advanced',
    minTier: 3, maxTier: 5,
    tags: ['radiation','space','energy'],
    timePressure: ['flare peak in twelve minutes','shielding overheating'],
    movementConstraints: ['radiation-safe corridors only','EVA forbidden','comms blackout'],
    collateral: ['crew of forty','automated farms outside'],
    dynamicFactors: ['secondary CME','grid trip'],
  },
  {
    id: 'orb-orbital-elevator-snap',
    title: 'Orbital Elevator Tether Snap',
    concept: 'A space elevator tether shears mid-climb; cable whipping back to surface.',
    category: 'sci-fi-advanced', scope: 'continental', intensity: 'cataclysmic', rarity: 'extreme',
    minTier: 3, maxTier: 5,
    tags: ['space','metal','infrastructure','energy'],
    timePressure: ['cable wrapping around equator','climber falling'],
    movementConstraints: ['fall path','airborne debris','climbers in distress'],
    collateral: ['ground anchor city','equatorial belt populations'],
    dynamicFactors: ['orbital counterweight loss','reentry fireballs'],
  },
  {
    id: 'orb-asteroid-mining-collapse',
    title: 'Asteroid Mining Rig Tunnel Collapse',
    concept: 'An asteroid spinrig tunnel collapses; centrifugal gravity throwing rock around.',
    category: 'sci-fi-advanced', scope: 'local', intensity: 'critical', rarity: 'advanced',
    minTier: 3, maxTier: 5,
    tags: ['space','rubble','rock','metal'],
    timePressure: ['spin destabilizing','rig venting atmosphere'],
    movementConstraints: ['variable gravity','floating debris','airless sections'],
    collateral: ['miners across multiple shifts'],
    dynamicFactors: ['rig spin loss','full cavern decompress'],
  },
  {
    id: 'orb-terraforming-runaway',
    title: 'Runaway Terraforming Atmosphere Conversion',
    concept: 'A terraforming station vents converter gas faster than the ecosystem can absorb.',
    category: 'sci-fi-advanced', scope: 'planetary', intensity: 'critical', rarity: 'extreme',
    minTier: 3, maxTier: 5,
    tags: ['toxic','wind','space','infrastructure'],
    timePressure: ['atmosphere shifting toxic','colonists losing breathable layer'],
    movementConstraints: ['toxic gas pockets','wind shifts','collapsing biodomes'],
    collateral: ['colonist towns','agricultural domes'],
    dynamicFactors: ['converter cascade','full atmospheric flip'],
  },
  {
    id: 'orb-ai-facility-lockdown',
    title: 'AI Facility Lockdown Going Hostile',
    concept: 'A research facility’s safety AI reinterprets its mandate and seals the campus.',
    category: 'sci-fi-advanced', scope: 'district', intensity: 'critical', rarity: 'advanced',
    minTier: 2, maxTier: 5,
    tags: ['energy','infrastructure','urban'],
    timePressure: ['next protocol activating','researchers locked in labs'],
    movementConstraints: ['sealed blast doors','suppression gas','autonomous turrets'],
    collateral: ['research staff','visiting families'],
    dynamicFactors: ['turret activation','networked spread'],
  },
  {
    id: 'orb-starliner-engine-flameout',
    title: 'Starliner Engine Flameout on Reentry',
    concept: 'A passenger starliner loses an engine on atmospheric reentry; burning across continents.',
    category: 'orbital-aerospace', scope: 'continental', intensity: 'cataclysmic', rarity: 'advanced',
    minTier: 3, maxTier: 5,
    tags: ['fire','metal','infrastructure','space'],
    timePressure: ['altitude bleeding off','no go-around'],
    movementConstraints: ['vibration shaking the cabin','plasma sheath','blacked-out comms'],
    collateral: ['hundreds of passengers','flight crew'],
    dynamicFactors: ['second engine failure','ditch in unpopulated zone'],
  },
  {
    id: 'sci-antimatter-containment-breach',
    title: 'Antimatter Containment Field Failing',
    concept: 'An antimatter battery’s magnetic bottle is fluctuating; engineers trying to drain it.',
    category: 'sci-fi-advanced', scope: 'district', intensity: 'cataclysmic', rarity: 'advanced',
    minTier: 3, maxTier: 5,
    tags: ['energy','radiation','infrastructure','metal'],
    timePressure: ['field oscillating into failure','drain only at limited rate'],
    movementConstraints: ['radiation-safe paths','magnetically shielded corridors','EM interference'],
    collateral: ['city block above','plant staff'],
    dynamicFactors: ['micro-annihilation pulse','grid loss'],
  },
  {
    id: 'sci-plasma-conduit-rupture',
    title: 'Plasma Conduit Rupture in Megafactory',
    concept: 'A 20MW plasma conduit ruptures in a megafactory, melting through walls.',
    category: 'sci-fi-advanced', scope: 'local', intensity: 'critical', rarity: 'advanced',
    minTier: 2, maxTier: 5,
    tags: ['fire','energy','metal','smoke','infrastructure'],
    timePressure: ['plasma jet eating through bulkheads','adjacent conduits next'],
    movementConstraints: ['radiant heat zones','molten floor','plasma backsplash'],
    collateral: ['production crew','automated transport bots'],
    dynamicFactors: ['second conduit failure','reactor scram'],
  },
  {
    id: 'sci-singularity-lab-instability',
    title: 'Lab Singularity Becoming Unstable',
    concept: 'A contained micro-singularity drifts off its trap; gravity readings going nonlinear.',
    category: 'sci-fi-advanced', scope: 'local', intensity: 'cataclysmic', rarity: 'extreme',
    minTier: 4, maxTier: 5,
    tags: ['gravity','energy','infrastructure'],
    timePressure: ['drift accelerating','room fixtures pulled inward'],
    movementConstraints: ['variable gravity','flying debris','hard radiation'],
    collateral: ['lab staff','adjacent campus'],
    dynamicFactors: ['singularity merger','hawking burst'],
  },
  {
    id: 'sci-hololith-reality-flicker',
    title: 'Hololith Projection Bleeding Into Reality',
    concept: 'A massive hololith generator overloads, projecting solid hard-light into a stadium.',
    category: 'sci-fi-advanced', scope: 'local', intensity: 'critical', rarity: 'advanced',
    minTier: 3, maxTier: 5,
    tags: ['energy','crowd','urban','infrastructure'],
    timePressure: ['projections becoming permanent','generator overheating'],
    movementConstraints: ['hard-light walls appearing','phantom obstacles','crowd panic'],
    collateral: ['stadium crowd','performers'],
    dynamicFactors: ['generator runaway','reality stitching'],
  },
  {
    id: 'sci-nano-swarm-loose',
    title: 'Manufacturing Nanoswarm Loose in Industrial District',
    concept: 'A manufacturing nanoswarm escapes containment; reshaping metals it touches.',
    category: 'sci-fi-advanced', scope: 'district', intensity: 'critical', rarity: 'advanced',
    minTier: 3, maxTier: 5,
    tags: ['toxic','metal','infrastructure','urban'],
    timePressure: ['swarm doubling every minute','nearby skybridge being eaten'],
    movementConstraints: ['eroding metal beams','swarm hot zones','no metal weapons'],
    collateral: ['workers','adjacent housing'],
    dynamicFactors: ['swarm sentience emergence','EMP option backfiring'],
  },
  {
    id: 'sci-graviton-storm',
    title: 'Graviton Storm Distorting District Gravity',
    concept: 'A graviton storm sweeps through a district, randomizing local gravity.',
    category: 'sci-fi-advanced', scope: 'district', intensity: 'critical', rarity: 'extreme',
    minTier: 4, maxTier: 5,
    tags: ['gravity','urban','energy','debris'],
    timePressure: ['storm peak in two minutes','buildings flexing'],
    movementConstraints: ['unpredictable gravity','flying objects','people lifting off'],
    collateral: ['street crowds','high-rise occupants'],
    dynamicFactors: ['gravity inversion','localized singularity flash'],
  },
  {
    id: 'pln-supervolcano-caldera',
    title: 'Supervolcano Caldera Beginning to Erupt',
    concept: 'A supervolcano caldera shows pre-eruption uplift; magma reaching the surface.',
    category: 'planetary-extreme', scope: 'continental', intensity: 'cataclysmic', rarity: 'extreme',
    minTier: 3, maxTier: 5,
    tags: ['fire','smoke','rock','wilderness'],
    timePressure: ['initial vents opening','catastrophic blast hours away'],
    movementConstraints: ['cracking ground','ash pulses','toxic gas pockets'],
    collateral: ['continental population','global air traffic'],
    dynamicFactors: ['ring-fault opening','volcanic winter pulse'],
  },
  {
    id: 'pln-magnetic-pole-flip-spike',
    title: 'Magnetic Pole Flip Aurora Surge',
    concept: 'An accelerating geomagnetic flip causes auroral plasma to reach ground level.',
    category: 'planetary-extreme', scope: 'planetary', intensity: 'critical', rarity: 'extreme',
    minTier: 3, maxTier: 5,
    tags: ['energy','radiation','infrastructure'],
    timePressure: ['next plasma pulse in minutes','grid collapse worldwide'],
    movementConstraints: ['unshielded electronics dead','plasma pillars','navigation lost'],
    collateral: ['everyone','everything connected'],
    dynamicFactors: ['secondary CME amplifying','satellites raining down'],
  },
  {
    id: 'pln-ocean-anoxic-pulse',
    title: 'Anoxic Ocean Pulse Releases Hydrogen Sulfide',
    concept: 'A coastal anoxic pulse releases massive hydrogen sulfide clouds inland.',
    category: 'planetary-extreme', scope: 'continental', intensity: 'cataclysmic', rarity: 'extreme',
    minTier: 3, maxTier: 5,
    tags: ['toxic','water','wind','wilderness'],
    timePressure: ['plume reaching coast in an hour','shelters running short'],
    movementConstraints: ['no breathable air outside','plume in low areas'],
    collateral: ['coastal cities','fishing fleets'],
    dynamicFactors: ['secondary release','rain making sulfuric acid'],
  },
  {
    id: 'pln-asteroid-airburst',
    title: 'Asteroid Airburst Over Populated Region',
    concept: 'A 100m asteroid airbursts above a populated region; shockwave en route to ground.',
    category: 'planetary-extreme', scope: 'continental', intensity: 'cataclysmic', rarity: 'extreme',
    minTier: 3, maxTier: 5,
    tags: ['fire','wind','rubble','urban'],
    timePressure: ['shockwave arriving in seconds','thermal flash already incoming'],
    movementConstraints: ['flattened structures','superheated air','glass storm'],
    collateral: ['regional population','aviation in flight'],
    dynamicFactors: ['secondary fragments','firestorm from ignited cities'],
  },
  {
    id: 'pln-core-quake',
    title: 'Mantle Convection Spike Triggers Continent Quake',
    concept: 'A mantle convection spike creates a continent-spanning quake swarm.',
    category: 'planetary-extreme', scope: 'continental', intensity: 'cataclysmic', rarity: 'extreme',
    minTier: 4, maxTier: 5,
    tags: ['rubble','rock','wilderness','urban'],
    timePressure: ['next quake in moments','tsunami chain inbound'],
    movementConstraints: ['ground rolling','collapsed cities','severed coasts'],
    collateral: ['multi-continent populations'],
    dynamicFactors: ['volcanic awakening','crustal rift'],
  },
  {
    id: 'myt-dimensional-tear-city',
    title: 'Dimensional Tear Above Skyline',
    concept: 'A reality tear opens above a skyline; alien geometries leaking into the city.',
    category: 'mythic-cosmic', scope: 'city', intensity: 'cataclysmic', rarity: 'mythic',
    minTier: 4, maxTier: 5,
    tags: ['energy','urban','gravity','space','darkness'],
    timePressure: ['tear widening','reality flicker in adjacent districts'],
    movementConstraints: ['gravity inversions','non-Euclidean streets','time dilation pockets'],
    collateral: ['city population','dimensional refugees pouring through'],
    dynamicFactors: ['second tear','entity emergence'],
  },
  {
    id: 'myt-ancient-seal-cracking',
    title: 'Ancient Seal Cracking Under Megacity',
    concept: 'A buried seal under a megacity is failing; an entity stirring beneath the streets.',
    category: 'mythic-cosmic', scope: 'city', intensity: 'cataclysmic', rarity: 'mythic',
    minTier: 4, maxTier: 5,
    tags: ['ruins','underground','urban','energy','darkness'],
    timePressure: ['next sigil failing','tremors increasing'],
    movementConstraints: ['warped corridors','dropping infrastructure','psychic interference'],
    collateral: ['city above','cult and counter-cult factions'],
    dynamicFactors: ['entity partial emergence','reality wave'],
  },
  {
    id: 'myt-collapsing-star-window',
    title: 'Collapsing Star Visible in Daytime Sky',
    concept: 'A nearby star collapses; gravitational wave front incoming, sky going wrong.',
    category: 'mythic-cosmic', scope: 'cosmic', intensity: 'cataclysmic', rarity: 'mythic',
    minTier: 5, maxTier: 5,
    tags: ['gravity','energy','space','darkness'],
    timePressure: ['wavefront in a minute','tides going chaotic'],
    movementConstraints: ['gravity ringing','time skipping','mass panic'],
    collateral: ['planetary biosphere'],
    dynamicFactors: ['secondary collapse','reality stretch'],
  },
  {
    id: 'myt-blackhole-flyby',
    title: 'Rogue Black Hole Near-Miss',
    concept: 'A rogue black hole passes through the outer system; planetary orbits warping.',
    category: 'mythic-cosmic', scope: 'cosmic', intensity: 'cataclysmic', rarity: 'mythic',
    minTier: 5, maxTier: 5,
    tags: ['gravity','space','energy','darkness'],
    timePressure: ['tidal pulse incoming','orbits destabilizing'],
    movementConstraints: ['extreme tides','gravity gradients','no comm'],
    collateral: ['everyone on the planet'],
    dynamicFactors: ['moon ejected','crustal tide'],
  },
  {
    id: 'myt-godform-awakening',
    title: 'Sealed Godform Awakening Beneath Mountain',
    concept: 'A sealed entity wakes inside a sacred mountain; the mountain itself standing up.',
    category: 'mythic-cosmic', scope: 'continental', intensity: 'cataclysmic', rarity: 'mythic',
    minTier: 4, maxTier: 5,
    tags: ['ruins','rock','rubble','energy','darkness'],
    timePressure: ['entity full waking imminent','region quaking'],
    movementConstraints: ['shifting terrain','reality shimmer','psychic pressure'],
    collateral: ['nearby civilizations','cultic factions'],
    dynamicFactors: ['attendant awakenings','sympathetic seals failing elsewhere'],
  },
  {
    id: 'wld-grizzly-attack-camp',
    title: 'Apex Predator Attack on Camp',
    concept: 'A startled apex predator charges through a backcountry camp at dusk.',
    category: 'wilderness-survival', scope: 'local', intensity: 'rising', rarity: 'grounded',
    minTier: 1, maxTier: 2,
    tags: ['wilderness'],
    timePressure: ['second pass coming','injured camper bleeding'],
    movementConstraints: ['tents and gear','low light','wet ground'],
    collateral: ['camp group','dog'],
    dynamicFactors: ['second predator drawn in','brush fire from kicked stove'],
  },
  {
    id: 'wld-quicksand-swamp',
    title: 'Quicksand Trap in Mangrove Swamp',
    concept: 'A film crew sinks into mangrove quicksand as the tide turns.',
    category: 'wilderness-survival', scope: 'local', intensity: 'rising', rarity: 'grounded',
    minTier: 1, maxTier: 2,
    tags: ['water','wilderness','flood'],
    timePressure: ['tide rising','sun setting'],
    movementConstraints: ['sucking mud','tangled roots','crocodile hazard'],
    collateral: ['stuck crew','equipment lost'],
    dynamicFactors: ['storm surge','wildlife converging'],
  },
  {
    id: 'wld-desert-flash-storm',
    title: 'Desert Flash Storm and Wash-Out',
    concept: 'A flash thunderstorm fills a normally-dry desert wash where a tour group is hiking.',
    category: 'wilderness-survival', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 2,
    tags: ['water','flood','wilderness','wind'],
    timePressure: ['wall of water in minutes','no signal'],
    movementConstraints: ['sheer canyon walls','slippery rock','strong current'],
    collateral: ['tourist group','guide'],
    dynamicFactors: ['second cell','rockfall'],
  },
  {
    id: 'wld-mountaineering-storm',
    title: 'Storm Pinning Climbers to Ridge',
    concept: 'A storm pins a roped team to an alpine ridge above 7000 meters.',
    category: 'wilderness-survival', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 2, maxTier: 4,
    tags: ['ice','wind','rock','wilderness'],
    timePressure: ['oxygen depleting','frostbite setting in'],
    movementConstraints: ['knife-edge ridge','whiteout','exposed traverse'],
    collateral: ['rope team','rescue helicopter unable'],
    dynamicFactors: ['cornice collapse','lightning strike'],
  },
  {
    id: 'wld-jungle-medevac',
    title: 'Jungle Medevac From Crash Site',
    concept: 'A bush plane goes down in dense jungle; survivors with major injuries.',
    category: 'wilderness-survival', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['wilderness','fire','metal','toxic'],
    timePressure: ['injured deteriorating','no clear LZ'],
    movementConstraints: ['triple canopy','swamp','wreckage','wildlife'],
    collateral: ['four survivors','rescue paramedics'],
    dynamicFactors: ['fuel fire','flash flood'],
  },
  {
    id: 'atm-mesospheric-fire',
    title: 'Mesospheric Plasma Sheet Sets Sky Aflame',
    concept: 'A solar event excites the mesosphere; the sky itself burns in colored sheets.',
    category: 'planetary-extreme', scope: 'planetary', intensity: 'critical', rarity: 'extreme',
    minTier: 3, maxTier: 5,
    tags: ['energy','radiation','wind','space'],
    timePressure: ['radio blackout','aircraft ionizing'],
    movementConstraints: ['EM interference','aurora glare','HF dead'],
    collateral: ['airline passengers','spaceport ops'],
    dynamicFactors: ['ground arcing','satellite reentry'],
  },
  {
    id: 'urb-elevator-freefall',
    title: 'Elevator Bank Freefall in Skyscraper',
    concept: 'A controller failure sends multiple elevators into freefall in a skyscraper.',
    category: 'mechanical-runaway', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['metal','urban','infrastructure','rubble'],
    timePressure: ['cars accelerating','safety brakes overheating'],
    movementConstraints: ['locked shafts','no rescue access','inertia inside'],
    collateral: ['lunchtime occupants','maintenance crews'],
    dynamicFactors: ['cable snap','counterweight strike'],
  },
  {
    id: 'inf-traffic-tunnel-flood',
    title: 'River-Tunnel Pump Failure During Flood',
    concept: 'Pumps fail in a road tunnel under a river during peak flood; tunnel filling.',
    category: 'water-flooding', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['water','flood','underground','urban','metal'],
    timePressure: ['water level rising','vehicles stalling'],
    movementConstraints: ['stranded cars','dark tunnel','rising water','live electrics'],
    collateral: ['rush-hour drivers','tunnel maintenance crew'],
    dynamicFactors: ['ventilation collapse','transformer arc'],
  },
  {
    id: 'fir-highrise-stack-effect',
    title: 'High-Rise Stack-Effect Inferno',
    concept: 'Stack effect drives flames up a high-rise core; multiple floors involved.',
    category: 'fire-conflagration', scope: 'local', intensity: 'cataclysmic', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['fire','smoke','urban','infrastructure'],
    timePressure: ['floor count rising','standpipe pressure failing'],
    movementConstraints: ['smoke-filled stairs','locked refuge floors','elevator off-limits'],
    collateral: ['residents','firefighters interior'],
    dynamicFactors: ['curtain wall fall','full-floor flashover'],
  },
  {
    id: 'med-mass-casualty-event',
    title: 'Mass Casualty Event at Public Venue',
    concept: 'Toxic substance released at a public venue; hundreds collapsing.',
    category: 'crowd-panic', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['toxic','crowd','urban'],
    timePressure: ['symptoms peaking','identification of agent unknown'],
    movementConstraints: ['unsafe air','panicked egress','ambiguous source'],
    collateral: ['venue crowd','first responders'],
    dynamicFactors: ['secondary device','runner spreading agent'],
  },
  {
    id: 'urb-skybridge-failure',
    title: 'Skybridge Connector Failure',
    concept: 'A glass skybridge between towers fails; people strung along its length.',
    category: 'urban-collapse', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['metal','urban','rubble'],
    timePressure: ['next bracket failing','wind loading rising'],
    movementConstraints: ['cracked glass floor','tilting platform','wind'],
    collateral: ['commuters in transit','window cleaners'],
    dynamicFactors: ['full bridge drop','adjacent tower damage'],
  },
  {
    id: 'inf-water-treatment-toxic',
    title: 'Water Treatment Toxic Backflow',
    concept: 'A backflow event sends toxic chemicals into a city’s drinking water mains.',
    category: 'chemical-radiological', scope: 'city', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['toxic','water','urban','infrastructure'],
    timePressure: ['plume reaching schools','isolation valves slow'],
    movementConstraints: ['contaminated taps','panicking shoppers','closed roads'],
    collateral: ['city population','restaurants and hospitals'],
    dynamicFactors: ['secondary contamination','ignition of flammable mix'],
  },
  {
    id: 'urb-brewery-tank-rupture',
    title: 'Brewery Pressure Tank Rupture',
    concept: 'A 200,000-liter brewery tank ruptures; flood of liquid through warehouse blocks.',
    category: 'mechanical-runaway', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 2,
    tags: ['water','flood','metal','urban'],
    timePressure: ['second tank shifting','workers under wave'],
    movementConstraints: ['liquid wave','floating barrels','slick floors'],
    collateral: ['shift workers','adjacent businesses'],
    dynamicFactors: ['CO2 release','floor collapse'],
  },
  {
    id: 'tra-cruise-ferry-fire',
    title: 'Car Ferry Fire on Open Sea',
    concept: 'A car deck fire on a packed ferry, smoke choking the upper decks.',
    category: 'maritime-deepwater', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['fire','smoke','metal','water'],
    timePressure: ['fire breaching firewalls','lifeboats overcrowded'],
    movementConstraints: ['narrow stairs','smoke','listing deck'],
    collateral: ['hundreds of foot passengers','vehicles with families'],
    dynamicFactors: ['fuel tank involvement','full power loss'],
  },
  {
    id: 'fir-paint-warehouse-bleve',
    title: 'Paint Warehouse Solvent BLEVE',
    concept: 'A solvent BLEVE blows the roof off a paint warehouse, igniting nearby blocks.',
    category: 'fire-conflagration', scope: 'district', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['fire','smoke','toxic','urban','metal'],
    timePressure: ['next drum stack heating','wind carrying embers'],
    movementConstraints: ['heat zones','collapsed roof','solvent puddles'],
    collateral: ['neighborhood','responders'],
    dynamicFactors: ['adjacent block fire','toxic smoke plume'],
  },
  {
    id: 'sub-coal-mine-flood',
    title: 'Coal Mine Flooded From Old Workings',
    concept: 'Modern mining cuts into flooded old workings; trapped crew underground.',
    category: 'subterranean-cavern', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 1, maxTier: 3,
    tags: ['water','flood','underground','rubble'],
    timePressure: ['water rising in shaft','rescue capsule still being prepared'],
    movementConstraints: ['narrow shafts','black water','lost lights'],
    collateral: ['trapped miners','rescue divers'],
    dynamicFactors: ['second inrush','methane pocket'],
  },
  {
    id: 'mar-hospital-ship-engine-fire',
    title: 'Hospital Ship Engine Room Fire',
    concept: 'An engine room fire on a deployed hospital ship; patients in surgery above.',
    category: 'maritime-deepwater', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 2, maxTier: 4,
    tags: ['fire','smoke','metal','water','infrastructure'],
    timePressure: ['halon depleted','ship power dropping'],
    movementConstraints: ['cramped engine room','smoke','heat'],
    collateral: ['patients in surgery','ship crew'],
    dynamicFactors: ['fuel tank involvement','blackout in OR'],
  },
  {
    id: 'mil-bunker-buster-aftermath',
    title: 'Underground Bunker Compromised After Strike',
    concept: 'A failing bunker after an unrelated strike; civilians trapped behind blast doors.',
    category: 'urban-collapse', scope: 'local', intensity: 'critical', rarity: 'grounded',
    minTier: 2, maxTier: 4,
    tags: ['underground','rubble','smoke','infrastructure'],
    timePressure: ['oxygen depleting','aftershock collapses pending'],
    movementConstraints: ['heavy blast doors','rubble','dust','no comms'],
    collateral: ['displaced civilians','staff'],
    dynamicFactors: ['secondary collapse','flooding from broken main'],
  },
  {
    id: 'inf-lng-terminal-spill',
    title: 'LNG Terminal Cryogenic Spill',
    concept: 'A pipe failure at an LNG import terminal; cryogenic liquid pooling on dock.',
    category: 'chemical-radiological', scope: 'district', intensity: 'critical', rarity: 'grounded',
    minTier: 2, maxTier: 4,
    tags: ['fire','ice','metal','toxic','infrastructure'],
    timePressure: ['vapor cloud reaching ignition source','deck steel embrittling'],
    movementConstraints: ['cryogenic burn zone','vapor cloud','no sparks'],
    collateral: ['terminal staff','nearby ships'],
    dynamicFactors: ['vapor cloud explosion','BLEVE'],
  },
];

// ── Selection Helpers ────────────────────────────────────────────

export function getBlueprintsByRarity(rarity: RarityTier): EmergencyBlueprint[] {
  return EMERGENCY_BLUEPRINTS.filter((b) => b.rarity === rarity);
}

export function getBlueprintsForTier(tier: number): EmergencyBlueprint[] {
  const t = Math.max(1, Math.min(5, Math.round(tier))) as SurvivabilityFloor;
  return EMERGENCY_BLUEPRINTS.filter((b) => t >= b.minTier && t <= b.maxTier);
}

export function getBlueprintById(id: string): EmergencyBlueprint | undefined {
  return EMERGENCY_BLUEPRINTS.find((b) => b.id === id);
}

export const BLUEPRINT_COUNT = EMERGENCY_BLUEPRINTS.length;
