DROP VIEW IF EXISTS public.characters_decrypted;

CREATE VIEW public.characters_decrypted
WITH (security_invoker=on) AS
SELECT
  id,
  user_id,
  level,
  age,
  created_at,
  updated_at,
  name,
  race,
  sub_race,
  home_planet,
  home_moon,
  image_url,
  sex,
  race_id,
  solar_system_id,
  stat_intelligence,
  stat_strength,
  stat_power,
  stat_speed,
  stat_durability,
  stat_stamina,
  stat_skill,
  stat_luck,
  stat_battle_iq,
  appearance_height,
  appearance_build,
  appearance_hair,
  appearance_eyes,
  appearance_distinct_features,
  appearance_clothing_style,
  appearance_aura,
  appearance_description,
  appearance_posture,
  appearance_voice,
  appearance_movement_style,
  appearance_typical_expression,
  decrypt_field(lore) AS lore,
  decrypt_field(powers) AS powers,
  decrypt_field(abilities) AS abilities,
  decrypt_field(personality) AS personality,
  decrypt_field(mentality) AS mentality,
  decrypt_field(weapons_items) AS weapons_items
FROM characters;